### ISSUE TITLE
Advanced Rocketry Crash

### ISSUE THREAD

**Issue by minty212** [tracer4b/nomi-ceu#101]
This is not a request, simply an identification of a repeated bug and a solution for it. My pack version is 1.4.

Sometimes my PC's OS crashes completely and has to restart. When this happens while playing the pack (through PolyMC), I ran into the issue of not being able to load into the world at all, with the client completely crashing. 

Looking into my log, the following line was directly preceding the line of Java closing the instance:
[Server thread/FATAL] [advancedrocketry]: A serious error has occured while loading the planetDefs XML
This was the only fatal error in the log, and was consistent on each attempt to load. 

Besides using backups, I found that by deleting planetDefs.xml -- or the entire Advanced Rocketry folder in the worldfile, which is what I did -- solves the problem. The files are recreated while loading into the world, with the only apparent consequence being the loss of the questbook's functionality (all tabs and quests are gone). This can be solved by creating a new Nomi instance and transferring saves over, and manually completing each quest that you had completed, preferably with the Designer feature while having edit mode enabled (/bq_user refresh doesn't work).

I have no experience with mod design, Java spaghetti, or Minecraft's filesystems, but I hope that this can help to pinpoint a bug.

**Comment by Folanlron** [comment]
As far as the OS problems, there is nothing we can do about it, the corruption occurs cause if MC is forcibly shutdown mid-save it will not "pause" the cancel and try and write the data too the file, it just straight up closes the java thread(which in you're case is you're PC crashing)

This is why sometimes it won't corrupt but most of the time it will corrupt.

and the Planetdefs.xml thing has been known for awhile... as well as a lot of AR issues ..

**Comment by tracer4b** [comment]
AR skill issue
