### ISSUE TITLE
Old recipe removal?

### ISSUE THREAD

**Issue by adamcirillo** [tracer4b/nomi-ceu#104]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4

**Description:**
2 recipes for auto breaker

**Expected Behavior:**
should only be one recipe

**Steps To Reproduce:**
check the recipe

**Screenshots:**
![image](https://user-images.githubusercontent.com/13363284/191605157-960a9124-1d0d-430a-9ad9-e57cf72775a4.png)

**Comment by tracer4b** [comment]
This is a wontfix honestly, it's not progression breaking nor a big deal
