### ISSUE TITLE
Quest "Genesis" completed but not unlocking other ones

### ISSUE THREAD

**Issue by arcmega** [tracer4b/nomi-ceu#107]
**Pack Version:**
1.4

**Description:**
In the quest book, the very first quest "Genesis" is completed, but strangely some quest needing genesis to be unlocked like "Spend your coins!" or "Primitive Steelworks" aren't unlocked while other are. I added some mods for performance (listed in the "steps to reproduce" section) but I don't think the issue come from there.

**Expected Behavior:**
The quests should be unlocked.

**Steps To Reproduce:**
Add the mods: "SwingThroughGrass","Ai Improvements","Entity Culling". Launch the modpack and create a world "Lost Cities". Just complete the first quest "Genesis" in the genesis tab and all the other one unlocked until you can't finish the genesis tab.

**Screenshots:**
![image](https://user-images.githubusercontent.com/114339291/192140518-0a337734-e556-4c84-858b-d1fbf7f37b05.png)
Genesis quest completed.
![image](https://user-images.githubusercontent.com/114339291/192140544-d88b222e-c724-4d29-a4e4-da2fabd56839.png)
Primitve Steelworks not unlocked.
![image](https://user-images.githubusercontent.com/114339291/192140649-9585746b-bf5c-45de-9402-780ba34d342e.png)
Other quests like "Spend your coins!" or "Terminal" also not unlocked.

**Comment by arcmega** [comment]
Some news: I tried to redo all the quest available in the quest book in creative but still nothing.
Also the thing that pop up on your screen saying that you finished a quest isn't there, I first thought that the modpack had removed it but now I'm wondering if it's related to this bug.

**Comment by Folanlron** [comment]
Do 

/bq_admin edit off

Known issue it's cause tracer shipped the lastest release with edit mode on accidentally...

**Comment by arcmega** [comment]
Thanks for the help !
