### ISSUE TITLE
Item Pipes not working?

### ISSUE THREAD

**Issue by FirewallDaProtogen** [tracer4b/nomi-ceu#108]
I will admit, i'm new to this modpack,  but i have tried every single thing to get item pipes to work and they dont. I have tried literally every single possible way of configuring the item pipes, but i can't even get just a single block of cobblestone to go from one chest to another just 1 block away.

**Comment by IntegerLimit** [comment]
Can you send a screenshot?

**Comment by FirewallDaProtogen** [comment]
![what](https://user-images.githubusercontent.com/113303660/192170215-42e2784c-6777-4b89-988e-681c377083bf.png)
I would think that at least one of the above images should transport an item some sort of direction, but it doesn't. even the 4 combinations on top mixed with the bottommost one don't do anything. i'm sure there is a chance i'm doing something wrong, but i've tried searching and cannot find any description of how item pipes are to be used to actually transport items

**Comment by IntegerLimit** [comment]
You need to have some kind of module importing into the item pipe, e.g. a conveyer.

**Comment by FirewallDaProtogen** [comment]
> You need to have some kind of module importing into the item pipe, e.g. a conveyer.

Ah, i see. what is a good early game one?

**Comment by IntegerLimit** [comment]
It would be better to ask these sorts of questions in the CEU channel in the nomifactory discord. However, in the early game, you can use ulv conveyers, or if you are not in 1.4, lv conveyers.

**Comment by FirewallDaProtogen** [comment]
thanks, i appreciate it
