### ISSUE TITLE
Void cake issue?

### ISSUE THREAD

**Issue by superhealing** [tracer4b/nomi-ceu#112]
**Pack Version:**
1.4

**Description:**
As server operator. We recieved complain that void cake doesn't *really* direct to randomized islands. 

**Expected Behavior:**
If first person got access to void cake, that locks as permanent. Any other people will get same island as original person.

**Steps To Reproduce:**
An online server (forge, nothing else). Have two alts or two friends (highly recommended). First person click void cake, second person also have separate cake. Directly links to original 1 island.

**Comment by Caedis** [comment]
Little late, but you want Island Cakes, not Void Cakes

They need to be enabled in the config file (and setup so it goes to the void dim (119))
Might want to also adjust the island gap.

**Comment by IntegerLimit** [comment]
> Little late, but you want Island Cakes, not Void Cakes
> 
> They need to be enabled in the config file (and setup so it goes to the void dim (119)) Might want to also adjust the island gap.

@superhealing does this fix it?
