### ISSUE TITLE
LCR recipe conflict

### ISSUE THREAD

**Issue by chinponya** [tracer4b/nomi-ceu#113]
**Pack Version:**
1.4

**Description:**
This LCR recipe for dinitrogen tetroxide makes nitrous oxide instead

![image](https://user-images.githubusercontent.com/58706956/193320202-a310c3da-173e-4c30-b3ab-79ff1d96bf56.png)

**Comment by IntegerLimit** [comment]
Check if you have two output hatches, so that the LCR can output both water and dinitrogen tetroxide. This happened to me too, and it was due to only having one output hatch.

**Comment by chinponya** [comment]
I'm fairly positive the setup is correct, unless the order of the hatches matters for some reason.
![2022-10-01_02 16 20](https://user-images.githubusercontent.com/58706956/193374949-6e5a4988-9b91-4e83-b1be-47b845982bed.png)
This is supposed to work, right? I'm not crazy?

**Comment by IntegerLimit** [comment]
Can you send a screenshot of the conflict recipe?

**Comment by chinponya** [comment]
Seems to be this one
![image](https://user-images.githubusercontent.com/58706956/193375527-0e9e66aa-c34c-46fb-b4ff-6a19c00f3696.png)

**Comment by IntegerLimit** [comment]
So... probably one of them should be changed... which one do you think should be changed, and to what circuit? Maybe it is to do with one being a LCR recipe and the other being a normal chemical reactor recipe.

**Comment by chinponya** [comment]
That would solve it.
Changing the LCR recipe makes more sense to me. I suspect it would affect fewer existing worlds, given it was not reported before.
I can't really tell if there is any pattern to how the circuit numbers were chosen, but 5 seems to be free.

**Comment by IntegerLimit** [comment]
Ok, thanks. I will quickly test if this is a GTCEU problem.

**Comment by IntegerLimit** [comment]
This seems to also be the case on just GTCEU, would you mind posting this in their issue tracker and closing this issue? @chinponya

**Comment by chinponya** [comment]
Sure. I should've posted it there to begin with.
