### ISSUE TITLE
[Hard] Rubber sheet alloy furnace recipe does not appear in JEI.

### ISSUE THREAD

**Issue by pudy248** [tracer4b/nomi-ceu#114]
In short, looking for rubber sheet recipes in JEI leads one to believe that there is no pre-LV way to make them, despite rubber sheets being required for LV machines. Putting the ingots in a steam alloy smelter with a plate mold does work, but it doesn't show up in JEI. This has caused several people no small amount of confusion.

**Comment by tracer4b** [comment]
Duplicate of GregTechCEu/GregTech#1163
