### ISSUE TITLE
Effortless building exception disconnects players from the server

### ISSUE THREAD

**Issue by Valor760** [tracer4b/nomi-ceu#116]
**Pack Version:** 1.4.1a
What changed in configs: 

- Storage drawers base size increased by 2
- Ender IO conduits allowed to connect with different tiers
-  Morpheus: SleeperPerc = 1

**Description:**
Playing with friends. People are randomly disconnected. What I see in console is:

[20:37:45] [Netty Server IO #2/ERROR]: There was a critical exception handling a packet on channel effortlessbuilding
java.lang.NullPointerException: null
[20:37:45] [Netty Server IO #2/ERROR]: Network Disconnect: A fatal error has occurred, this connection is terminated
[20:37:45] [Server thread/INFO]: JustMisery lost connection: A fatal error has occurred, this connection is terminated
[20:37:45] [Server thread/INFO]: §eJustMisery§r§e left the game§r

When asking people, what last they've done, the answer are various starting from "broke the block"/"placed the block", ending with "wrote in the chat".

I personally never had this issue, so I investigated further and what found out, that everyone who is disconnecting constantly, they've updated from1.4.0 to 1.4.1a in the courseforge to the **same** profile, while I've downloaded to the separate one. But there is no difference in EffortlessBuilding.cfg files and mod versions are the same too.

**Comment by tracer4b** [comment]
Since installing to a different profile works, go with that and see if that fixes the issue.
Most modpack handlers have serious issues updating packs

**Comment by Valor760** [comment]
As an update, everyone has done nothing and hasn't experienced this issue never again. Probably, it was a one time issue (maybe connection one, or server internal, but after restart it fixed itself).
Closing this one.
