### ISSUE TITLE
Gamerules are being reset upon loading world/pack

### ISSUE THREAD

**Issue by DoomSquirter** [tracer4b/nomi-ceu#119]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4.1a

**Description:**
gamerules should be persistent.  but for some reason, they get reverted to defaults when you load a world.
tested: doWeatherCycle, doMobGriefing
someone said keepinventory is also reset
edit:
note: this did not happen in 1.3.5 which is what I updated from.

**Expected Behavior:**
They shouldn't reset every time you load the world up.  Once set, they should be persistent till you change them

**Steps To Reproduce:**
change a gamerule and save/quit to menu and reload world and notice the gamerule has been reset

**Crash Log:**
If your client crashed as a result of this bug, please upload the generated crash log. This is found in your launcher's Nomifactory profile (aka instance) in a folder called `crash-reports`. If there was no crash, but instead an error screen, please upload your `latest.log` instead.

**Screenshots:**

**Comment by Ale5432** [comment]
I have the same problem

**Comment by IntegerLimit** [comment]
Same thing happens to me as well.

**Comment by khthe8th** [comment]
This happened to me as well, and I'm not sure if it's new or not but the resolution is to modify globalgamerules.cfg in the config folder. If you modify it there it will save and persist through server/game restarts
