### ISSUE TITLE
I think my world corrupted pls help I keep having this problem pop up.

### ISSUE THREAD

**Issue by Ale5432** [tracer4b/nomi-ceu#121]
https://pastes.dev/RrIN1jKJX4

**Comment by Ale5432** [comment]
https://pastes.dev/FKO7w0qucQ

**Comment by enderger** [comment]
Have you tried loading from a backup (FTB backups should be in the pack if I remember correctly).

**Comment by tracer4b** [comment]
Stale, loading from backup should/should have resolve/d the issue
