### ISSUE TITLE
Simulation Supercomputer won't run with any craftable data models

### ISSUE THREAD

**Issue by ChachavaMC** [tracer4b/nomi-ceu#123]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4.1a

**Description:**
After building the supercomputer and feeding it power, a stack of polymer clay and giving it one my Ender Dragon data models...nothing happened. I thought it may need to be a freshly crafted model, but that also didn't work. As a last resort I cheated in a fresh model without any data and this seemed to work fine.

**Expected Behavior:**
The machine to work with any craftable data model regardless of tier.

**Steps To Reproduce:**
Just creating the structure and having it form correctly, craft a data model of any kind and then feed that along with polymer clay into the input hatch. 

**Screenshots:**
Machine not working with a crafted data model
![2022-10-06_17 10 23](https://user-images.githubusercontent.com/43357764/194364415-24e38cf5-e78b-4371-b13f-ecb0c19cd22a.png)

Machine lights up and starts working with a cheated in fresh data model
![2022-10-06_17 10 46](https://user-images.githubusercontent.com/43357764/194364435-f3feeb3b-6a2e-4f05-a3a6-efe0cbba6845.png)

**Comment by tracer4b** [comment]
This is a bug with reading recipe input NBT data, same as #84.
It has to be fixed CEu-side, it will next update

**Comment by IntegerLimit** [comment]
Fixed with 1.4.2. Please close this issue.
