### ISSUE TITLE
Lazy AE compat script error

### ISSUE THREAD

**Issue by MadMedicineMan** [tracer4b/nomi-ceu#124]
**Pack Version:**
1.4.1a

**Description:**
Error when installing LazyAE; script misses ";" in Line 16. --> Disables recipe for wrought iron

**Expected Behavior:**
No errors wenn using this script, wrought iron still obtainable through smelting iron in a regular furnace

**Steps To Reproduce:**
Install Lazy AE V 1.1.26 via direct drop into mod folder, load world.

**Possible Fix**
Include ";" in Line 16 in []\Nomifactory (GTCEu Port)\scripts\ModSpecific\LazyAE2.zs

**Comment by Dirkprutser** [comment]
Additional note: I also had a problem that electrolyzing clay dust was a 60 eu/t MV recipe, breaking progression. After fixing the error by adding a semicolon to line 15 of LazyAE2.zs (<ore:dustCoal>.remove(<threng:material:3>) to <ore:dustCoal>.remove(<threng:material:3>);) this error was fixed. Reproduced by doing the same fix to a clean install and world.

**Comment by MadMedicineMan** [comment]
Issue should be fixed in a future update :) #18265d
