### ISSUE TITLE
Missing Alloy Blast Smelter Recipes

### ISSUE THREAD

**Issue by IntegerLimit** [tracer4b/nomi-ceu#125]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4.1a, Normal Mode

**Description:**
For some alloys, there are missing alloy blast smelter recipes.

**Expected Behavior:**
For each alloy that needs a mixer to have an alloy blast smelter recipe.

**Steps To Reproduce:**
For example, Samarium Iron Arsenic Oxide and Mercury Barium Calcium Cuprate do not have recipes shown in JEI/HEI

**Comment by IntegerLimit** [comment]
This will be a slow fix, requiring a check of each blast furnace alloy, but I feel like it is worth it.

**Comment by IntegerLimit** [comment]
Is this a GCYM issue or a nomi issue?

**Comment by tracer4b** [comment]
Some alloys (End Steel etc) just don't have ABS recipes.
Those two you mentioned should have them though. I believe it's because they have fluids in their mixer recipes. Report to GCYM

**Comment by IntegerLimit** [comment]
Just as a side note, signalum and lumium both also have fluids in their mixer recipes, and they have ABS recipes.

**Comment by tracer4b** [comment]
Those are custom materials and I added their recipes manually. The existing materials should have autogenerated

**Comment by IntegerLimit** [comment]
it seems that the code generating the recipes specifically stops at fluids. I guess we should add custom alloy blast recipes for them.
