### ISSUE TITLE
16a UHV energy converts show negative max integer power.

### ISSUE THREAD

**Issue by ChachavaMC** [tracer4b/nomi-ceu#126]
**Pack Version:**
1.4.1a

**Description:**
UHV 16a energy converters show a negative max integer number for energy amount and won't output any power. This was using a Draconic superconductor conduit. With a regular draconium conduit the power level stays at 0.

**Expected Behavior:**
The converters to work as others do, plug power in, face it into an energy hatch and you're good to go (provided you have the power there)

**Steps To Reproduce:**
Place down 16a UHV energy hatch, place down 16a UHV converter facing into the hatch, give rf power to the converter.

**Screenshots:**
https://gyazo.com/436553cd18944ff7e99a9a502db18a06

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).
