### ISSUE TITLE
OutOfMemoryError when clicking "back" betterquesting

### ISSUE THREAD

**Issue by h3tR** [tracer4b/nomi-ceu#127]
**Pack Version:**
[1.4.1a](https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4014120)

**Description:**
Whenever I click "back" after focusing on a quest in the quest book the game crashes and throws a OutOfMemoryError.
It is likely caused by a recursive method  going haywire I think.

**Expected Behavior:**
Instead of crashing it should return to the quest book.

**Steps To Reproduce:**
I don't know how to reproduce it.
All I know is that it happened after a fresh install of the pack without using curseforge (I run ubuntu so that is not available).

**Crash Log:**
[Crash Log](https://pastes.dev/YBW4k6E66v)

**Comment by tracer4b** [comment]
Closing as a BQ issue
