### ISSUE TITLE
LazyAE2.zs

### ISSUE THREAD

**Issue by IAmNotGEM** [tracer4b/nomi-ceu#130]
row15: <ore:dustCoal>.remove(<threng:material:3>) (**here missing a ";"**)
row16: mods.jei.JEI.removeAndHide(<threng:material:3>);

ERROR: [crafttweaker | SIDE_CLIENT]: Error parsing ModSpecific\LazyAE2.zs:16 -- ; expected

**Comment by Folanlron** [comment]
Already fixed in a recent pull from Tracer, just sense LazyAE2 is not a "primary" mod a update won't be pushed cause of it.

**Comment by tracer4b** [comment]
Fixed in 18265d61f06a35498c07d532dc6022860a01df3c

**Comment by IAmNotGEM** [comment]
> Fixed in [18265d6](https://github.com/tracer4b/nomi-ceu/commit/18265d61f06a35498c07d532dc6022860a01df3c)

OKay
