### ISSUE TITLE
Adding optional mods changes receips and makes quest progress impossible 1.4.1a

### ISSUE THREAD

**Issue by udooles** [tracer4b/nomi-ceu#132]
I started a new world and was able to craft things like the steam dynamo but after adding the optional mods AE2 Fluid Crafting, Compact Machines, Flux Networks and Lazy AE2 the receipt for crafting the dynamo includes a part that is not craftable.  Other receipts like the nether cake are also uncraftable with no way to light the nether portal.  

If I recreate the profile in Curseforge and copy the world back the receipts seem to restore.

**Comment by udooles** [comment]
I disabled the four mods and what I believe is the correct crafting receipts for the steam dynamo and nether cake was restored.   The exact version of the mods I installed was

compactmachines3-1.12.2-3.0.18-b278
fluid craft for ae2-2.4.1-r
fluxnetworks-1.12.2-4.1.1.34
lazy-ae2-1.12.2-1.1.26

**Comment by Folanlron** [comment]
It's because there is a bug in the lazyae2 script..

If CT catches a error it just stops trying too load, so you get half-loaded scripts..

You can fix it by doing this in the lazyae2 script..

https://github.com/tracer4b/nomi-ceu/commit/18265d61f06a35498c07d532dc6022860a01df3c

**Comment by tracer4b** [comment]
Closed as fixed in https://github.com/tracer4b/nomi-ceu/commit/18265d61f06a35498c07d532dc6022860a01df3c
