### ISSUE TITLE
Suggestion: Change Graphene Programmable Circuit Number

### ISSUE THREAD

**Issue by DevJRoc** [tracer4b/nomi-ceu#136]
Hi All - I believe this conflict arises because I've heard that Graphene's recipe was made easier, but the issue is that if I have Graphene and Tungstensteel recipes sharing a bus on my Mixer Array, it can risk making Tungstencarbide. I believe that the programmable circuits were designed with the intention of ensuring that any given recipe using that circuit should always make the right byproduct, even with blocking mode off. I would recommend utilizing Circuit 2 as part of the Graphene recipe change to resolve.

Thanks so much for your work on the pack - I've been having a blast with it!

**Comment by IntegerLimit** [comment]
You can use blocking mode on your interface, resulting in the interface not putting in the autocraft's items into the mixer array if there are items inside them. Note, blocking mode also ignores integrated circuits. Therefore, I do not believe this is needed.

**Comment by DevJRoc** [comment]
That's fair. I figured I should turn off blocking mode to get more out of my arrays without multiplying the pattern i/o, but I should probably just bulkify my patterns or create a separate bus.

**Comment by IntegerLimit** [comment]
Closed as not intended.
