### ISSUE TITLE
AE2 Network tool crash

### ISSUE THREAD

**Issue by Kaio-Cesar** [tracer4b/nomi-ceu#137]
**Pack Version:**
1.4.1a (Curseforge)

**Added mods:**
Lazy AE2
Compact Machines
AE Fluid Crafting Rework
Flux Networks

**Description:**
When using the AE2 network tool, it crashes, and the interface don't show the network properly.

**Expected Behavior:**
It should show the ae2 network, how many blocks, power, etc.

**Steps To Reproduce:**
Just use the network tool on some ae2 block.

**Crash Log:**
https://pastes.dev/Rpq24JECRH

**Screenshots:**
[Bug.webm](https://user-images.githubusercontent.com/43482905/196519806-3e82ffc9-4c7d-4018-bce3-6a14aabeb72a.webm)

**Comment by Kaio-Cesar** [comment]
I tried removing AE2 Fluid crafting rework, the crash persist

**Comment by IntegerLimit** [comment]
This should probably be on the Pae2 Github. This happens to me too, with just the base pack.
https://github.com/PrototypeTrousers/Applied-Energistics-2
Close this issue, and post it there.

**Comment by tracer4b** [comment]
Closing as an AE2 issue
