### ISSUE TITLE
Cannot fix "Genesis bug" without cheats

### ISSUE THREAD

**Issue by PlasticBa** [tracer4b/nomi-ceu#138]
I have cheats turned off, but when trying to find a solution to this bug, all of them require cheats turned on.

Edit: here is an image
![genesis quest not working](https://user-images.githubusercontent.com/95364628/197050672-f8026cb5-c5a9-44aa-be2a-b6b851cb767c.png)

**Comment by IntegerLimit** [comment]
Yeah, your going to have to have cheats turned on. For an easy way to get cheats enabled, you can press 'esc' on your keyboard, press 'open to lan', and then change it to cheats on. This will last until you 'quit and save to title'.

**Comment by tracer4b** [comment]
This should have been fixed in the latest release, make sure to do `/bq_admin default load`
