### ISSUE TITLE
Thermal Recipes wont work/lost their custom recipes

### ISSUE THREAD

**Issue by Itplayz** [tracer4b/nomi-ceu#140]
**Pack Version:**
1.4.1a

**Description:**
Custom Recipes are gone and replaced by the default recipes and some recipes wont work at all. Even after changing to the old 1.4 Version the recipes are still not working properly

**Expected Behavior:**
Custom working recipes

**Steps To Reproduce:**
Open 1.4.1a and check recipes for redstone coils/numismatic dynamos/machine frames etc.

**Screenshots:**
![image](https://user-images.githubusercontent.com/109357944/198873929-2c6c9d9a-f329-4fe7-a50f-cf79c2e1097c.png)
![image](https://user-images.githubusercontent.com/109357944/198873941-9bb01538-b06a-4984-afc3-93dd703084eb.png)

**Comment by HikerL** [comment]
Have you add LazyAE2 to your package? If so just turn to #130 andit has been Fixed in [18265d6](https://github.com/tracer4b/nomi-ceu/commit/18265d61f06a35498c07d532dc6022860a01df3c) . Do as the change in the LazyAe2.zs

**Comment by IntegerLimit** [comment]
I believe that this has been fixed. If this occurs again on 1.5, and you are not using the CurseForge Launcher, which has problems launching this pack, please reopen this issue.
