### ISSUE TITLE
The Configurable Maintenance Hatch doesn't work as its description 

### ISSUE THREAD

**Issue by HikerL** [tracer4b/nomi-ceu#142]
**Pack Version:**
1.4.1a-with all addable mods that nomi-ceu mentioned

**Description:**
Multiblocks(issues founded in Electric Blast Furance) with a Configurable Maintenance Hatch doesnot need maintence and the adjustable options don't work(nothing happens to duration when I configure the magnification)

**Expected Behavior:**
The Configurable Maintenance Hatch should cut off 10% duration on recipes of EBF as I configure the  magnification in the Hatch

**Steps To Reproduce:**
Just put it on.

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).
