### ISSUE TITLE
zh_cn.lang

### ISSUE THREAD

**Issue by IAmNotGEM** [tracer4b/nomi-ceu#143]
https://github.com/IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN/releases

**Comment by tracer4b** [comment]
Does this supersede #133?

**Comment by IAmNotGEM** [comment]
> 

yes, that one i closed.

**Comment by tracer4b** [comment]
Ok the pack handles translations somewhat differently and it'll take a while for me to figure it out. Thanks for the contribution

**Comment by tracer4b** [comment]
Refer to #164
