### ISSUE TITLE
Naquadah Reactor MK1 & MK2 quest inconsitency 

### ISSUE THREAD

**Issue by khthe8th** [tracer4b/nomi-ceu#144]
**Pack Version:**
1.4.1a

**Description:**
Naquadah Reactor MK1 quest requires 3 omnium trimmed blocks of black steel, but the reactor itself calls for only 1, plus 2 blocks of duranium (not listed as a quest requirement)

Naquadah Reactor MK2 quest requires 5 blocks of omnium, reactor itself only calls for 1, plus 3 blocks of ruthenium trinium americium neutronate (not listed as quest requirement)

**Expected Behavior:**
Quest book requirements should match what is required to create the reactors. Currently if following the quest book you have the wrong materials and unable to make reactors.

**Steps To Reproduce:**
View Naquadah Reactor MK1 and MK2 quests under "Late Game" tab of quest book

**Crash Log:**
N/A
**Screenshots:**

**Comment by khthe8th** [comment]
Also MK1 quest asks for transparent fission reactor casing instead of fusion glass

**Comment by IntegerLimit** [comment]
Thanks for the notice, has been fixed in Big Quest Fix, will be ready to merge into main soon.
