### ISSUE TITLE
Peaceful is no longer locked by default in Hard Mode

### ISSUE THREAD

**Issue by Targuinia** [tracer4b/nomi-ceu#146]
**Pack Version:**
[097f298](https://github.com/tracer4b/nomi-ceu/commit/097f298ee446c68d8426683f14459c5765163acd), but any version from  [46e1936](https://github.com/tracer4b/nomi-ceu/commit/46e1936dfe0520f1e72434f37a08d5bc2531d0c7).

**Description:**
The removal of Global Gamerules also means the `globalgamerules.cfg` from the expert configs no longer applies, and peaceful is no longer locked.  
It should probably be replaced with a separate difficulty locking mod.

**Comment by IntegerLimit** [comment]
What would you recommend?

**Comment by tracer4b** [comment]
implemented in 1afc9f64859092beb251a7e31c4488f4428ff507

**Comment by IntegerLimit** [comment]
> implemented in [1afc9f6](https://github.com/tracer4b/nomi-ceu/commit/1afc9f64859092beb251a7e31c4488f4428ff507)

Should this be closed?
