### ISSUE TITLE
Item Guide not showing any info

### ISSUE THREAD

**Issue by Abdulrehman-Zia** [tracer4b/nomi-ceu#149]
The item guide in the terminal doesn't display any info for most of the items
![image](https://user-images.githubusercontent.com/74990534/202603918-2fb82eec-7a08-4761-bfcb-f3a16e9c5c35.png)
![image](https://user-images.githubusercontent.com/74990534/202604157-5569a21b-9bc4-4481-a5aa-da98f97e36d6.png)
![image](https://user-images.githubusercontent.com/74990534/202604250-7ea5864b-9063-44ad-9a62-48279e18e131.png)

**Comment by IntegerLimit** [comment]
That's GTCEu's fault, and it is because they don't have the time to fill it in. If you would like, you could contribute some descriptions in their github. Please close this issue.

**Comment by tracer4b** [comment]
throw to CEu
