### ISSUE TITLE
(hard mode) backwards quest dependency

### ISSUE THREAD

**Issue by kmod** [tracer4b/nomi-ceu#150]
Playing v1.4.2 on curseforge, hard mode

I'm at the point of building my first mk2 fusion reactor, and I noticed that some of the quests have dependencies in the wrong order, I think due to the cleanroom change.

In particular the wetware circuits require a sterilized cleanroom, which requires tritanium, which requires a mk2 fusion reactor. But the quest for the mk2 fusion reactor is locked behind the wetware circuits rather than the other way around.

As far as I can tell this is just a quest issue, not an actual progression issue -- I haven't finished building the mk2 fusion reactor but so far I haven't seen anything that requires wetware circuits / components. It's just a minor annoyance that I don't get to read the quest description while building the reactor, and I am not sure if I'll have to go back and re-complete it later.

**Comment by kmod** [comment]
yes and yes

**Comment by kmod** [comment]
Though I guess I should be careful -- I had created some bacterial sludge (for green-square-circuit-things) before the cleanroom update, which was unavailable to me afterwards. I think that my usage of the sludge was fine because I could have used europium instead, so while I believe I didn't skip any gates via this I'm not 100% sure.

**Comment by IntegerLimit** [comment]
Thanks! I’ll take a look at it.
