### ISSUE TITLE
No way to package Draconic Super conductor into 2x/4x/8x/16x

### ISSUE THREAD

**Issue by HikerL** [tracer4b/nomi-ceu#151]
**Pack Version:1.4.1a with all the mods mentioned in Github.

**Description:**
There is no recipe to package Draconic Super Conductor(MAX) into 2x/4x/8x/16x, neither crafting table or the packer, so I want to know if it's the original design.

**Screenshots:**
As shown in the screenshots, there is no recipe for the Draconic Super Conductor(MAX) in a packer or a crafting table. (it's in Chinese but I think you can recognize the Draconic Super Conductor(MAX) by Voltage)

![b453303f15e6cc0c46bd04577768fad](https://user-images.githubusercontent.com/35104870/202924789-79182485-e236-4330-82d7-c1ef70418bab.png)

**Comment by JunChengZzz** [comment]
这种问题是你客户端自己的问题。重装看看

**Comment by IntegerLimit** [comment]
No, this is an actual issue. The 'unification' recipes were removed to make it so you can only use the wires, but that also removed the merging and splitting recipes of the wires.

**Comment by IntegerLimit** [comment]
Working on it.

**Comment by HikerL** [comment]
> Working on it.

Thanks for your efforts！
