### ISSUE TITLE
sterilized cleanroom doesn't count as a normal cleanroom

### ISSUE THREAD

**Issue by kmod** [tracer4b/nomi-ceu#153]
Not sure if this should be considered a nomi-ceu issue or a gtceu issue, apologies if this is in the wrong place.

I just noticed that my sterilized cleanroom won't run any "requires cleanroom" recipes inside of it. Digging through the gtceu code I see that ICleanroomProvider is able to return multiple cleanroom types that are enabled, but the cleanroom entity [only returns a single type](https://github.com/GregTechCEu/GregTech/blob/88736e8a57ea46e81485b2a44a4221c7ef760b5f/src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java#L498).

Is this intentional? It's a bit annoying that some recipe chains require some cleanroom and some sterilized-cleanroom recipes.

**Comment by IntegerLimit** [comment]
Yes, this is intentional, meant to encourage you to build multiple cleanrooms.
