### ISSUE TITLE
No backups

### ISSUE THREAD

**Issue by kmod** [tracer4b/nomi-ceu#156]
I discovered this the hard way, but despite ftbbackups being included and running periodically, there are no backups stored anywhere.

**Comment by kmod** [comment]
Oh weird, I checked the other computer I play on and there are some there, but it seems like there are way fewer than expected

**Comment by IntegerLimit** [comment]
Yeah, the default config is 2 hours per backup, so unless so play for 2 hours, no backup. You can change this, however.

**Comment by CrossElectronics** [comment]
I changed the timer to 0.2h, works well when actively playing. The catch is that you can potentially fuck up forever if something goes wrong when you are afk.

**Comment by tracer4b** [comment]
Issue can be resolved individually, won't fix
