### ISSUE TITLE
Client crashing while using HEI/JEI

### ISSUE THREAD

**Issue by NeveHanter** [tracer4b/nomi-ceu#158]
**Pack Version:**
Nomifactory (GTCEu) from CurseForge, version 1.4.2

**Description:**
Sometimes when searching or scrolling through HEI/JEI the client crashes. No particular search query or anything, sometimes adding just one letter to the search crashes the client.

I've tried updating HEI and "Enough" packages along with the CCL without success (that's why I have it on more recent version than the one in the pack), both original and updated versions crash with the same error.

I was able to reproduce it both on Linux (with and without updated mods) and and Windows (without updated mods).

You can also ignore resource packs from the crash log, they change nothing.

I've had no such issues prior to the 1.4.2 update.

**Crash Log:**
https://pastes.dev/ykVv2pLqPO

**Comment by HikerL** [comment]
I have met the same issues in three versions from 1.40 to 1.42 actually, so it might be the issues caused by the HEI

**Comment by IntegerLimit** [comment]
Maybe report to HEI? I'm not sure tho.

**Comment by HikerL** [comment]
> I have met the same issues in three versions from 1.40 to 1.42 actually, so it might be the issues caused by the HEI

And I doubt it might be caused by Mouse Tweak by the record of the issues
