### ISSUE TITLE
Naquadah Reactor 2 crashing server

### ISSUE THREAD

**Issue by sreny1** [tracer4b/nomi-ceu#159]
**Pack Version:**
Nomifactory (GTCEu Port) v1.4.2

**Description:**
Naquadah Reactor 2 crashes Server
Experienced on Server first, then multiple times in a newly created singleplayer superflat world
crashed every time i put in fuel

**Expected Behavior:**
Server does not crash, Naquadah Reactor 2 generates EU

**Steps To Reproduce:**
1. Build a Naquadah reactor 2
2. put in fuel ( i used enriched Naquadah Bolts)
3. crash

**Crash Log:**
crash report: https://mclo.gs/p97xfBq
latest.log https://mclo.gs/DmOromU

**Screenshots:**

**Comment by sreny1** [comment]
Multiblock Tweaker version 2.4.4 fixes this issue

**Comment by IntegerLimit** [comment]
Can you link to the version of Multiblock Tweaker that works?

**Comment by sreny1** [comment]
my bad, idk what version number i was looking at there. updated the comment above - its this one:
https://www.curseforge.com/minecraft/mc-mods/multiblocktweaker/files/4083612

**Comment by IntegerLimit** [comment]
Yeah, that makes sense. MBT 2.4.4 :) 
You were probably looking at GTCEu version 2.4.4.
