### ISSUE TITLE
AE not letting add items

### ISSUE THREAD

**Issue by Executorder** [tracer4b/nomi-ceu#161]
![AE Issue](https://user-images.githubusercontent.com/20650260/205463053-699aa7c0-a6c8-4c5e-8012-c441d8e5b37d.png)
AE wont let me add the reciepe even all the items are in the system
even tried having them in inventory wont work in AE, but works in a reg crafting table

edit: seems to be the circuits that AE does not allow the use of

**Comment by Trouty** [comment]
I am facing a similar issue. Have you found a fix?
