### ISSUE TITLE
"Explore Actually Additions" Quest references unobtainable "Vertical digger"

### ISSUE THREAD

**Issue by joendter** [tracer4b/nomi-ceu#162]
**Pack Version:**
1.5

**Description:**
The "Explore Actually Additions" Quest references the "Vertical Digger" which is unobtainable and probably got replaced by GT miners.

**Expected Behavior:**
Just don't talk about it.

**Steps To Reproduce:**
Open Questbook, unlock all quests, look at the Explore Actually Additions Quest

**Screenshots:**

![grafik](https://user-images.githubusercontent.com/71767955/205488901-875d7fc3-8497-4ecd-87ad-20a5c71110d4.png)

**Comment by IntegerLimit** [comment]
Ok, thanks for the notice, I’ll have a look at it.
