### ISSUE TITLE
Infinite upgrade withdrawal inside The Ender storage

### ISSUE THREAD

**Issue by fXMM** [tracer4b/nomi-ceu#163]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Pack Version: 1.4.2

Added mods:
Bewitchment 1.12-0.0.22.64
Carryon  1.12.2-1.12.6.20
FluxNetworks- 1.12.2-4.1.1.34
Guide-API-1.12.2-4.1.1.34
ThaumicJEI-1.12.2-1.6.0
IronChest 1.12.2-7.0.72.847
DimensionalDoors-1.12.2-3.0.12
Blood Magic 1.12.2-2.4.3-105
Botania+r1.10-364.4
Thaumcraft-1.12.2-2.4.3-105
Psi r1.1-78.2
Astral sorcery-1.12.2-1.10.27
Totemic-1.12.2-0.11.6
Compact Machines 3 1.12.2-3.0.18-b278

**Description:**
I'm not sure if this is a common issue with EnderIO or if something in Nomifactory is causing it, but this issue piques my curiosity. An upgrade item placed inside of the storage of a "The Ender" sword can occasionally be withdrawn infinitely like a Creative Quantum Chest. 

**Expected Behavior:**
The correct behavior is for the inside of the sword to function as a storage cell for upgrades, not as a replicator for upgrades.

**Steps To Reproduce:**
Place an item within the storage module of The Ender, close the menu and dilly-dally for a bit, then re-open it.

**Screenshots:**
![2022-12-06_04 24 01](https://user-images.githubusercontent.com/34150300/205911913-0dc2393d-2689-4f71-a1b3-b4cc8b99acb7.png)
![2022-12-06_04 24 05](https://user-images.githubusercontent.com/34150300/205911959-364ac7b3-cafd-40ad-a253-149216ac24b8.png)

**Comment by IntegerLimit** [comment]
This is known, is a problem with Ender io, and cannot be fixed. However, since this doesn’t affect gameplay much as  this isn’t a combat based pack, it is fine.

**Comment by tracer4b** [comment]
Won't fix / throw to Ender IO
