### ISSUE TITLE
Crash when scrolling through the Microblock CBE Creative tab

### ISSUE THREAD

**Issue by dan96kid** [tracer4b/nomi-ceu#166]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**

Nomifactory CEu version 1.5

**Description:**
When scrolling through the Microblock CBE tab in the Creative inventory menu, the game crashes at somewhere around two thirds to three quarters of the way to the tab's bottom

**Expected Behavior:**
You can scroll all the way through the Microblock CBE tab without crashing.

**Steps To Reproduce:**
Scroll down the Microblock CBE tab in the creative mode inventory to somewhere around two thirds to three quarters of the way to the bottom.

**Crash Log:**

[crash-2022-12-11_13.55.21-client.txt](https://github.com/tracer4b/nomi-ceu/files/10203165/crash-2022-12-11_13.55.21-client.txt)

**Screenshots:**

**Comment by ProTriforcer** [comment]
This seems to be a GTCEu issue, same as #158 
For some reason Forge Microblocks can't generate microblocks out of ebf coils and some casings, but tries to render them anyway and crashes

**Comment by PrototypeTrousers** [comment]
yes, same reason as #158
fixed in gtceu by GregTechCEu/GregTech/pull/1294
