### ISSUE TITLE
The Naquadah Reactor 1 & 2 Crashes the game.

### ISSUE THREAD

**Issue by JuanDaniel2510** [tracer4b/nomi-ceu#169]
**Pack Version:** 1.4.2

**Description:**
Both Naquadah Reactors crashed the game when I push fuel into them.

**Steps To Reproduce:**
I use 1 ULV Input and 1 ULV Output for items and a ZPM 4A Dynamo (Naquadah Reactor 1) or UV 4A Dynamo (Naquadah Reactor 2) for energy output. When I Try to put a Enriched Naquadah Bolt or a Naquadria Bolt the game crashes. After that I have to use mcedit to delete the multiblock in order to go back in to the save.

**Crash Log:**
[crash-2022-12-14_17.21.22-server.txt](https://github.com/tracer4b/nomi-ceu/files/10230268/crash-2022-12-14_17.21.22-server.txt)

**Screenshots:**
![2022-12-14_17 20 58](https://user-images.githubusercontent.com/7580835/207666079-20921c24-f351-45a6-a142-a73b1d95a638.png)
![2022-12-14_17 20 51](https://user-images.githubusercontent.com/7580835/207666089-b23c44ad-5c28-472b-bcf0-14df9b0c75d1.png)

**Extra Info.:**
I don't know if it is important but i use Prism Launcher 6.0

**Comment by Folanlron** [comment]
Fixed via , https://github.com/tracer4b/nomi-ceu/issues/159

Just a new build hasn't been pushed yet.

**Comment by JuanDaniel2510** [comment]
oh ok, sorry! Didn't see that one.
