### ISSUE TITLE
Crash when upgrading from 1.4 to 1.4.2 Cause by Block tick on Naqaudria reactor block

### ISSUE THREAD

**Issue by Plainedge** [tracer4b/nomi-ceu#170]
**Pack Version:**
1.4.2

**Description:**
Upgraded from 1.4 to 1.4.2. Was able to log on to the world but after a short time (about a minute) the world crashed and would not open again. Crash report claims that a naquadria reactor block was attempting to tick at time of crash.

**Expected Behavior:**
Update should not cause crash

**Steps To Reproduce:**
Build a naquadria reactor MK 2 in 1.4 and then update to 1.4.2.

**Crash Log:**
[crash-2022-12-15_03.02.56-server.txt](https://github.com/tracer4b/nomi-ceu/files/10233429/crash-2022-12-15_03.02.56-server.txt)

**Screenshots:**
N/a

**Comment by Folanlron** [comment]
Fixed https://github.com/tracer4b/nomi-ceu/issues/159 

Just no build has been pushed yet...

**Comment by Plainedge** [comment]
Thank you.
