### ISSUE TITLE
Nether Not Optional due to Neon

### ISSUE THREAD

**Issue by player19375** [tracer4b/nomi-ceu#176]
**Pack Version:**
Nomifactory CEu v1.4.2

**Description:**
Neon can only be obtained by distilling nether air, which requires going to the nether. Since most of the pack is already designed with avoiding the nether in mind, an alternative method should be provided to allow players to skip the nether entirely. The exact recipe added can be up to further discussion. One possible solution is to add a fusion recipe for neon (plasma). 

**Expected Behavior:**
Neon can be obtained by means other than distilling nether air. 

**Steps To Reproduce:**
Check the recipes of neon in JEI. 

**Crash Log:**
No crash log

**Comment by player19375** [comment]
The end isn't optional due to chorus flower (not chorus plant) anyway, just like in base Nomi. But the end is also required for ender air, which is the only source of xenon and krypton, and a good source of deuterium (instead of the moon in base Nomi), tritium and radon in Nomi CEu. 
Speaking of optional dimensions, skipping the moon has barely any drawbacks since the lunar mining rover is made obsolete by ender air. The nether is only required due to neon iirc, as was mentioned before.

**Comment by tracer4b** [comment]
Closed by adding a recipe from T2 microminer.
