### ISSUE TITLE
You can't make cauldron with the Assembler.

### ISSUE THREAD

**Issue by trainvoi** [tracer4b/nomi-ceu#177]

**Comment by trainvoi** [comment]
The recipe isn't running. Personally, I think it's because it's conflicting with the hopper recipe.

**Comment by Folanlron** [comment]
uhh
 stick a circuit 7 in the assembler with 7 iron plates, works perfectly fine for me =p

**Comment by IntegerLimit** [comment]
> The recipe isn't running. Personally, I think the reason is the cauldron recipe is conflicting with the hopper recipe.

Is it making the hopper then? If it isn’t, you probably don’t have power going to the assembler or something.

**Comment by trainvoi** [comment]
The machine does have power:
![image](https://user-images.githubusercontent.com/51245052/209515871-741231ad-a06e-4d17-9916-8ca60ca592ea.png)
the machine isn't disabled by soft hammer either.

**Comment by tong-ge** [comment]
According to JEI, the cauldron needs number 7 and the hopper needs a chest, so they're not conflicting.Actually the goal of the programming circuit is for avoiding conflicts.

**Comment by IntegerLimit** [comment]
Closed, as it works well for everyone.
