### ISSUE TITLE
Client does not have same version of CensoredASM that the server files have.

### ISSUE THREAD

**Issue by TheResinger** [tracer4b/nomi-ceu#182]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
Nomifactory GTCEu 1.4.3

**Description:**
The server files were recently updated with the 5.6 version of CensoredASM but the client is still running 5.2 so upon trying to connect to an updated server you are met with a mod version mismatch error.

**Comment by SalGema** [comment]
I'am having the same issue.

**Comment by RRoland80** [comment]
Me too

**Comment by zedle** [comment]
Same here.

**Comment by zedle** [comment]
Figured it out. Delete loliasm-5.2 from client, copy over censoredasm-5.6 from server pack.

**Comment by 0xC4DE** [comment]
+1 Same issue on release version 1.4.3, It's fixed in main, but not in release.
