### ISSUE TITLE
Crash during the lunch of minecraft

### ISSUE THREAD

**Issue by SaYiiTo21** [tracer4b/nomi-ceu#183]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
NomiFactory 1.4.3

**Description:**
While lunching the game during the loading screan arriving to the 4/7 the loading stop and show this error even after trying to replace all the mod they asked nothing changed. I'm on ArchLinux

**Expected Behavior:**
Launching the game correctly.

**Steps To Reproduce:**
Installing the modpack and launching it.

**Crash Log:**
If your client crashed as a result of this bug, please upload the generated crash log. This is found in your launcher's Nomifactory profile (aka instance) in a folder called `crash-reports`. If there was no crash, but instead an error screen, please upload your `latest.log` instead.

**Screenshots:**

[crash-2022-12-30_19.16.45-client.txt](https://github.com/tracer4b/nomi-ceu/files/10325849/crash-2022-12-30_19.16.45-client.txt)
![Screenshot_2022-12-30_19-19-55](https://user-images.githubusercontent.com/110563633/210101203-f14fdbe1-fdfe-4280-ad44-d02488b55fed.png)

**Comment by Sequaren** [comment]
I recently received an identical error. I am using manjaro linux.
Crashlog - https://mclo.gs/flxP5wA
