### ISSUE TITLE
Steam Grinder quest has incorrect retrieval task

### ISSUE THREAD

**Issue by BronsonMagnan** [tracer4b/nomi-ceu#189]
**Pack Version:**
1.4.3

**Description:**
Steam grind quest asks for 22 Bronze Hulls, but the multiblock requires 22 Bronze Machine Casings

**Expected Behavior:**
For the quest to match the mutliblock casing requirements

**Steps To Reproduce:**
Open the questbook, compare against JEI multiblock preview

**Comment by benmontour** [comment]
Just threw a PR in for a fix for this. Just awaiting review and merge if approved.

**Comment by benmontour** [comment]
@IntegerLimit let me know that this is fixed in his #186 PR. Closed my PR (#194).
