### ISSUE TITLE
Electric implosion compressor requires TNT for recipes

### ISSUE THREAD

**Issue by Valor760** [tracer4b/nomi-ceu#191]
**Pack Version:** release-1.4.3

**Description:** Electric implosion compressor still requires TNT or Dynamite to process recipes. I don't know if this is an expected behavior, but if so - there is no difference between regular Implosion Compressor and Electric one.

**Expected Behavior:** Electric implosion compressor processes recipes without using TNT or Dynamite.

**Comment by Folanlron** [comment]
Expected behavior as the benefit of the Electric One is the fact it can Parallel

**Comment by Valor760** [comment]
@Folanlron Excuse me? Where does it have any parallel processing?
![image](https://user-images.githubusercontent.com/31585840/211256898-221cb8e5-d593-4b2a-a06f-c916e5dab919.png)
No parallel hatch in the structure

![image](https://user-images.githubusercontent.com/31585840/211256941-801fd87e-e52f-42b1-b1fa-49f4b17b256e.png)
The structure is not complete when placing parallel hatch

![image](https://user-images.githubusercontent.com/31585840/211256975-7c596420-6e95-49b0-81ca-de3ac54b6647.png)
Without the hatch structure is complete

**Comment by Folanlron** [comment]
I never built it, but I asked the devs about it and they said it will always require explosives, and that the benefit of the Electric one was Parallel, 

So I never built it cause of the whole what 3-4 recipes that actually require it, seems a bit too much =p

**Comment by Valor760** [comment]
Well, the same, I need it for now for lapis and certus, since everything in dusts :D
I just thought, it should work as in GTHN modpack, where electric one is more expensive, but doesn't require explosives. Seems, it's not the case, unfortunately.

Also, I thought if I could myself resolve this issue by adding recipes into scripts, but I found out 2 problems:
1) For some reasons I can't find "electric_implosion_compresson" tile entity in RecipeMap
2) Seems like GTCEu has a mandatory to contain an explosive :/
Maybe I missed something, not a java programmer tho.

Anyway, thanks for answers!
