### ISSUE TITLE
Formula Issue

### ISSUE THREAD

**Issue by ES-BitJump** [tracer4b/nomi-ceu#193]
**Pack Version:**
1.4.3
**Description:**
AE can not be used to synthesize Advanced Capacity Bank in the formula of Vibrant Capacity Bank
**Expected Behavior:**
Formula problems may occur in the NBT attribute of Advanced Capacity Bank in the Vibrant Capacity Bank formula
**Screenshots:**
![1](https://user-images.githubusercontent.com/66249006/211458604-e5b3344a-00e8-41eb-b4a9-6f90645fd671.jpg)

**Comment by IntegerLimit** [comment]
Try encoding the recipe with a crafted Advanced Capacitor Bank, instead of one from JEI.
