### ISSUE TITLE
Correction on README.md

### ISSUE THREAD

**Issue by 0xC4DE** [tracer4b/nomi-ceu#196]
In the README.md, to installed the expert modpacks it says
`MacOS and GNU/Linux users can run curl -s https://raw.githubusercontent.com/tracer4b/nomi-ceu/main/pack-mode-switcher.sh | sh in the pack root directory (the one containing /config).`

This command `curl -s https://raw.githubusercontent.com/tracer4b/nomi-ceu/main/pack-mode-switcher.sh | sh` does not work, as tested on arch.
It is also heavily discouraged that you curl into bash *ever*.

Instead I think it should say something along these lines

MacOS and GNU/Linux users can, in the root directory of the modpack (containing config directory),  run `curl -O https://raw.githubusercontent.com/tracer4b/nomi-ceu/main/pack-mode-switcher.sh` then verify the contents of the file. After this run `chmod +x pack-mode-switcher.sh` and run it with `sh pack-mode-switcher.sh` After it is run, it can be safely deleted.

If you guys would prefer this be a fork/pull request, I can do that and bind this issue to that pull.

**Comment by IntegerLimit** [comment]
Yeah, since you know how to fix it, I would recommend this be a PR instead. Thanks in advance!

**Comment by 0xC4DE** [comment]
Can be closed with #203
