### ISSUE TITLE
Oredict Filter Freezing Game

### ISSUE THREAD

**Issue by Correlander** [tracer4b/nomi-ceu#198]
**Pack Version:**
Release 1.4.3, happens in 1.5

**Description:**
Not sure if this should be reported to the pack git or the greg mod git itself, but my oredict filter is going off screen and then subsequently freezing my game when I try and make any filter that's too long. It's perfectly within character limit. It just goes off the screen and won't make new lines, only will actually freeze once I try using a ! operator.

**Expected Behavior:**
Normally when the text hits the edge of the window it makes a new line and you are able to scroll.

**Steps To Reproduce:**
Type in the spot where you type for an oredict filter. Continue typing. If it goes out of the window something is already wrong, but even further typing a ! will make things more wrong with a game freeze.

**Crash Log:**
No crash. It just indefinitely freezes. I'm not sure how to give you the latest log, it was too big for pastebin limit (512kb) being about 1mb. 

[latest.log](https://github.com/tracer4b/nomi-ceu/files/10610176/latest.log) is a latest.log where this happens.

[latest.log](https://github.com/tracer4b/nomi-ceu/files/10610187/latest.log) is where it happened, just with GTCEu, CodeChicken, GCYM and HEI.

**Screenshots:**
![image](https://user-images.githubusercontent.com/53982700/211977153-62812fb2-5321-4927-b280-2401e7e0782a.png)

**Extra**
My pack is ever so slightly altered, but it shouldn't affect this at all. I still say this because I know mods can have really weird interactions. The only alterations were the addition of better diving, and hidden armor mods, they should show in the mod load list in the paste.

**Comment by IntegerLimit** [comment]
Try reporting it to the GTCEu GitHub.

**Comment by IntegerLimit** [comment]
Does this still happen?

**Comment by IntegerLimit** [comment]
In my testing, the text still goes off the screen, but there is no freeze, or crash.

**Comment by Correlander** [comment]
> 

Try using different symbols near where it's on the edge of the screen. I think I was using a & or a ! if memory serves? I did find something similar after further testing where it was some symbol I did that would crash it, but only if it was off the edge of the screen. And I'll go report it there, thanks for the response.

**Comment by IntegerLimit** [comment]
Um.... Does it still happen in 1.5?

**Comment by Correlander** [comment]
Yeah

**Comment by IntegerLimit** [comment]
Ah, I just froze my game.

**Comment by IntegerLimit** [comment]
[latest.log](https://github.com/tracer4b/nomi-ceu/files/10610176/latest.log)

**Comment by IntegerLimit** [comment]
You don't seem to have reported it to GTCEu Github. https://github.com/GregTechCEu/GregTech/issues. I can do it instead, if you want.

**Comment by Correlander** [comment]
> You don't seem to have reported it to GTCEu Github. https://github.com/GregTechCEu/GregTech/issues. I can do it instead, if you want.

Yeah I managed to navigate there and I've had the page open for filling out an issue report for awhile now, I just am an extreme procrastinator and as there is no deadline I haven't done it yet. And no worries, I don't want to make you do it. I'll do it right now.

**Comment by Correlander** [comment]
Can I close the issue on this end?

**Comment by IntegerLimit** [comment]
You can leave it. I'll close it when GTCEu gets updated here.

**Comment by IntegerLimit** [comment]
Fixed next GTCEu.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/tracer4b/nomi-ceu/commit/3cc787ffb8fa7b6ac262e836c06f6c84c0f78359.
