### ISSUE TITLE
Hard Mode LV Electrolyzer quest description misleading

### ISSUE THREAD

**Issue by lily-es** [tracer4b/nomi-ceu#199]
**Pack Version:**
1.4.3 - Hard Mode

**Description:**
In Hard Mode, in the LV questline, the LV Electrolyzer quest mentions electrolyzing coal dust. But this recipe is MV, so this description is misleading. This should probably be changed to mention glass dust or some other method of getting silicon at LV.

**Comment by IntegerLimit** [comment]
I'll take a look at it. Thanks!
