### ISSUE TITLE
1.5.0 Crash when looking at Forge microblocks cover in HEI

### ISSUE THREAD

**Issue by zedle** [tracer4b/nomi-ceu#202]
**Pack Version:**
1.5.0

**Description:**
When opening HEI and in any way trying to have it render the forge microblocks cover game crashes to CCL crash handler screen. I am using a 128x texture pack if that makes any difference (worked fine under 1.4.3).

**Expected Behavior:**
Probably not do that

**Steps To Reproduce:**
1. Open inventory
2. Search @forge
3. Explode

**Crash Log:**
https://mclo.gs/aGldzmD

**Comment by zedle** [comment]
This does seem to have something to do with resourcepacks. When I enable different resource packs some of them now cause this issue. They didn't in 1.4.3. Vanilla has no issues as far as I can tell.
Using sphax purebdcraft with the omnifactory patches (https://bdcraft.net/community/releases-for-packs-f10/omnifactory-t7153.html) primarily.

**Comment by IntegerLimit** [comment]
Seems it might be a JEI Utilities issue. Might be fixed with https://github.com/tracer4b/nomi-ceu/commit/15b3daa90d04287ac67945e2956bf748998665d7. I don't know. Can you try updating your jei utils and see if that fixes it?
