### ISSUE TITLE
Burning oil underground due to lava causes massive performance issues

### ISSUE THREAD

**Issue by Vildis** [tracer4b/nomi-ceu#204]
**Pack Version:**
1.5

**Description:**
I noticed that randomly my computers case fans would ramp up to 100% and with further testing i found out it was only happening when looking towards the same direction every time. Using spectator mode and the case fans as indicators of the problem, i found oil and lava right next to each other with the oil burning. 

[map_backup.zip](https://github.com/tracer4b/nomi-ceu/files/10420457/2023-01-15-16-55-48.zip)

**Steps To Reproduce:**
Load the attached map, go to coordinates -50, 22, 155, look towards fire.

**Screenshots:**
![Image of the fire](https://user-images.githubusercontent.com/22894537/212548371-f6c71920-4968-4e86-b36f-dd662f4bf16e.png)

**Comment by Vildis** [comment]
Spark profile of world switching between looking at the fire and away https://spark.lucko.me/O41BPXptqW

**Comment by IntegerLimit** [comment]
Can you close this issue and upload to https://github.com/GregTechCEu/GregTech/issues?page=2&q=is%3Aissue+is%3Aopen here instead?

**Comment by IntegerLimit** [comment]
Please report to https://github.com/GregTechCEu/GregTech/issues instead.
