### ISSUE TITLE
I can't craft rubber sheets 

### ISSUE THREAD

**Issue by LittleTimmy52** [tracer4b/nomi-ceu#205]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5

**Description:**
There's a crafting recipe for rubber sheets, even the quest book says ya can craft them, but i put them in the table and there's nothing to grab, it's as if the recipe didn't even exist.

**Expected Behavior:**
I put a hammer in the top middle with 2 sticker resin below and it crafts into a rubber sheet 

**Steps To Reproduce:**
Get a hammer, get sticky resin, get a crafting table, attempt to craft rubber sheets in a crafting table 

**Crash Log:**
N/A

**Screenshots:**
![1673827832606742366061923674612](https://user-images.githubusercontent.com/90333044/212575036-c7c2652b-0bc8-46a9-9d72-040511090556.jpg)

![16738277350171435762432285463313](https://user-images.githubusercontent.com/90333044/212574966-e74bafbe-7e88-4157-8a96-06599f1b929d.jpg)

**Comment by LittleTimmy52** [comment]
Nvm, this is already posted, and it has a fix

**Comment by Xalorous** [comment]
The workaround is here:

https://github.com/tracer4b/nomi-ceu/issues/201#issuecomment-1383048888

Note: the first workaround only works with undamaged iron hammers, the second works with any gregtech hammers, in any damage state.
