### ISSUE TITLE
Minecraft stops responding when looking at certain turbine rotors' tooltips

### ISSUE THREAD

**Issue by omegazion** [tracer4b/nomi-ceu#206]
**Pack Version:**
1.5.0

**Description:**
When you mouse over at certain turbine rotors in the wireless terminal, the game stops responding. Also in JEI turbine rotors say Tooltip Error.
Not all turbine rotors. It doesn't happen with aluminium but definitely happens on HSS-S

**Expected Behavior:**
Respond. Show actual tooltip for turbine rotors instead of tooltip error.

**Steps To Reproduce:**
1. Put a HSS-S turbine rotor in AE2.
2. Use wireless terminal and search for it.
3. Mouse over it.

**Screenshots:**
![bug](https://user-images.githubusercontent.com/45467133/212581294-03c95fcb-746c-40b9-9207-aef24e71e2c1.png)

**Comment by IntegerLimit** [comment]
It has been reported to GTCEu, hopefully, it should be fixed before next update.

**Comment by IntegerLimit** [comment]
Changed the name to make it more clear.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/tracer4b/nomi-ceu/commit/3cc787ffb8fa7b6ac262e836c06f6c84c0f78359.
