### ISSUE TITLE
Suggestion: GregTech Food Option compat

### ISSUE THREAD

**Issue by RuneZhevitz** [tracer4b/nomi-ceu#208]
If it's not too much of a liability, an addon script for [GregTech Food Option](https://www.curseforge.com/minecraft/mc-mods/gregtech-food-option) would be great. It's an actively developed addon specifically for GTCEu that adds a load of foods from GT 6 with extremely greggy processing chains, and I feel like it would make food suitably greg for this pack since vanilla food (and most of the modded foods in this pack) is gregologically challenged.

**Comment by IntegerLimit** [comment]
The problem is that it also needs GCYS, which has been deemed to advanced for nomi. You can try adding both GCYS and GTFO, which should work.

**Comment by RuneZhevitz** [comment]
I don't see any indication that GCY:S is a _required_ dependency for GTFO. GTFO's mcmod.info only has gregtech as a dependency and the main class has GCY:S as an optional soft-dependency:
`dependencies = "required-after:gregtech@(2.3.4,);" + "after:gcy_science"`

**Comment by IntegerLimit** [comment]
Try just adding it? I think GTFO chains are still too advanced and complex for Nomi CEu, which is designed as a beginner pack into GregTech.

**Comment by tracer4b** [comment]
It doesn't look like GTFO needs any sort of config script to be added, it should work OK out of the box.

If someone contributes an addon script for it, I'd be willing to accept it
