### ISSUE TITLE
Recipe error in expert mode

### ISSUE THREAD

**Issue by CmmmmmmLau** [tracer4b/nomi-ceu#210]
**Pack Version:**
1.5

**Description:**
After load my save, a error info pop out in the chat
`Failed to hide recipe category: deepmoblearning.trial_keystone, caused by java.lang.IllegalArgumentException: Unknown recipe category: deepmoblearning.trial_keystone`

**Expected Behavior:**
Should no error pop out.

**Steps To Reproduce:**
Load any world in expert mode, should be able to see the error info in the chat.

**Screenshots:**
![20230116211104](https://user-images.githubusercontent.com/42691172/212766324-7c39595a-78bd-47c3-8112-6eddfb099cf0.png)

**Comment by IntegerLimit** [comment]
Yep, thanks for the notice, I'll have a look at it.
