### ISSUE TITLE
Ender IO Conduits: Round Robin no longer works in version 1.5

### ISSUE THREAD

**Issue by CarePlay** [tracer4b/nomi-ceu#211]
**Pack Version:**
Latest curse forge version 1.5

**Description:**
Round Robin for specifically Item conduits simply does not work/is ignored

**Expected Behavior:**
Round Robin should normally send items to multiple machines at once and not prioritize a certain machine

**Steps To Reproduce:**
Have one stack of an item that you want to input into several other machines and watch it put the whole stack in a single machine

**Screenshots:**
![2023-01-15_16 27 29](https://user-images.githubusercontent.com/82731351/212775485-22a11590-3d3d-4b73-90de-1f79975994a5.png)
![2023-01-15_16 27 24](https://user-images.githubusercontent.com/82731351/212775489-706cc05e-eb1c-4648-9a04-525eb490477a.png)

**Comment by IntegerLimit** [comment]
Um... have you tried with other inventories?

**Comment by CarePlay** [comment]
Yes, having just a simple 1 chest into 2 other ones also doesn't work.

**Comment by Armagedon13** [comment]
I have the same issue, I have a large system with drawers and drawer controller, so I can replace all ME until I have blank patterns, round robin just put the different inputs in the machines, but if the input to the machines are the same, the system just try to fill the first machines and later the other ones, I try everything and I can't make it work. Maybe find others pipes like gt pipes or xnet.

**Comment by Americangerman1** [comment]
I have tested this, the amount taken from a drawer seems to be 4 per tick and all of the fabricators I used got the same amount even with different materials. I also used crate to crate, and drawer to drawer with the same result.
I don't know if this was fixed but I can't recreate what is shown above. 
I did not test with an ME interface as the source of material so that might be the issue if the conduit is forced to take a full stack at a time.

**Comment by IntegerLimit** [comment]
OK, crazy idea, try using another launcher if you are using the CF one. Like Prism, for example.

**Comment by IntegerLimit** [comment]
Did my previous idea fix it? Does this issue still happen in 1.5.1?

**Comment by CarePlay** [comment]
Uh it's unfixable? It's an issue with EnderIO itself I found out. I installed standalone EnderIO in a fresh forge instance and the issue persists. And I think ender IO 1.12 isn't supported anymore ?

**Comment by Armagedon13** [comment]
I tested with MultiMC, PolyMC and PrismLauncher and the problem persist, so the issue is with ender IO, i have this problem long ago with nomi and nomi ceu. 

Tested in custom pack and the problem persist, ender IO issue.

**Comment by IntegerLimit** [comment]
> I have tested this, the amount taken from a drawer seems to be 4 per tick and all of the fabricators I used got the same amount even with different materials. I also used crate to crate, and drawer to drawer with the same result. I don't know if this was fixed but I can't recreate what is shown above. I did not test with an ME interface as the source of material so that might be the issue if the conduit is forced to take a full stack at a time.

Huh

**Comment by IntegerLimit** [comment]
Yeah, EIO is not being supported anymore, no one wants to rewrite it because of it's bad code.

**Comment by IntegerLimit** [comment]
The interesting thing is that 1.4.3 and 1.5 have the same version of EIO.

**Comment by CarePlay** [comment]
I'll close this now, thanks for the help offered. EnderIO conduits will be bad in 1.12 ig.
