### ISSUE TITLE
Nomicoins

### ISSUE THREAD

**Issue by poggerslime** [tracer4b/nomi-ceu#213]
**Pack Version:**
1.4.2

**Description:**
Nomicoins are called omnicoins in questbook.

**Expected Behavior:**
Nomicoins should be renamed to omnicoins

**Steps To Reproduce:**
Open questbook

**Crash Log:**
N/A

**Screenshots:**

**Comment by IntegerLimit** [comment]
Can you update to 1.5 and see if the issue persists?

**Comment by IntegerLimit** [comment]
Ah, thanks. I'll take a look at it now.
