### ISSUE TITLE
Machines consuming an additional copy of AE2 requested items.

### ISSUE THREAD

**Issue by Yakobro** [tracer4b/nomi-ceu#214]
I have greg machines auto exporting to drawers connected to AE2 via controllers with storage buffers set to export only. The machines take items in from interfaces with items being pulled from them.

When the system takes items out of the drawers for other machines interfaces twice that amount disappears from the machines internal output if the drawer was full when the items were requested.
I've looked through a few machines that are processing amounts limited enough to notice and it's happening to at least multiple machines.
I noticed it first with my SMD Diodes being pulled to make EV Workstations, it should only consume 4 Diodes however 8 would vanish from the assemblers internal output each craft. It is also at least happening to my extruder making NZF-Rings. Due to how quick needing to know how many of an item is requested it's hard to test many others.

Setting a robot arm to export to the drawer at under the drawers cap makes the problem not occur.

Version 1.5.0

- Just tested having a conveyor pull instead to a full drawer, same problem. Tried on a fresh install too -

**Comment by IntegerLimit** [comment]
This seems to be a Storage Drawers and PAE2 issue. Can you report this to the PAE2 GitHub instead?

**Comment by IntegerLimit** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/207

**Comment by IntegerLimit** [comment]
Closed with https://github.com/tracer4b/nomi-ceu/commit/e29388a616b762e37de08c32becb0c87e223a73c.
