### ISSUE TITLE
Butchery knives no longer have looting III in 1.5

### ISSUE THREAD

**Issue by buizerd** [tracer4b/nomi-ceu#215]
Is this intended with the "rebalancing tool stats" change? Before 1.5 all butchery knifes had Looting III. In 1.5 only the Damascus Steel knife has Looting III. When playing Hard mode in peaceful Minecraft, the butchery knife is one of the only (good) ways of gathering experience early game.

[edit]
The 1.5 Butchery knifes also do a lot less damage but do area of effect damage (which is annoying when having an animal farm and you'll kill the babies 😄)

**Comment by IntegerLimit** [comment]
Ask GTCEu.

**Comment by buizerd** [comment]
You are right, it's a GTCEu change. I was under the impression that the Butchery knive's looting enchantment was an original Nomifactory feature.
