### ISSUE TITLE
Add quest description for how to use Gregicality's Voltage Control Unit

### ISSUE THREAD

**Issue by trainvoi** [tracer4b/nomi-ceu#217]
The voltage control unit is very important because it basically allows you to underclock the voltage the machine is using
For example, a multiblock is receiving 4A of EV. With an MV Voltage control unit, the machine will interpret this as 64A of MV power, making it possible for the multi-block to use ZPM Parallel hatches (64 recipes at the same time)

If you are reading this, can you add the option for tin item pipe in Genesis?

**Comment by IntegerLimit** [comment]
I believe it automatically will turn into 64A of MV in this scenario, if you were to just place a ZPM parallel hatch. Can you check this?

Also, yes,I working to make the GT item pipes quest accept any item pipe.

**Comment by trainvoi** [comment]
seems like the gregicality multiblocks don't accept voltage control unit. I tried used the debug function of the Mulitblock Helper, and it doesn't show the voltage control unit as a valid building block:
![image](https://user-images.githubusercontent.com/51245052/213866593-34d0de9c-ab0c-4a26-8bc7-c5185372c421.png)

**Comment by IntegerLimit** [comment]
> 

This is because the Voltage Control Units are a config, which can be used to gate voltages.
E.g. you can only run it at EV if you have EV Control Unit
And the config is disabled in NFu.

**Comment by IntegerLimit** [comment]
I've removed the voltage control units in #207.
Tin was recommended and any item pipe allowed in #186

**Comment by IntegerLimit** [comment]
Closed as resolved. Voltage Control Units are useless and have been removed. Tin is now the recommended item pipe, and any item pipe is now accepted, in the development branch https://github.com/tracer4b/nomi-ceu/tree/qb-dev.
