### ISSUE TITLE
Lapotron crystal NBT Charge tag remains on discharged crystals, preventing use in engraver

### ISSUE THREAD

**Issue by fishsicles** [tracer4b/nomi-ceu#218]
**Pack Version:** 1.5

**Description:** Placing a lapotron crystal that has previously been charged into a laser engraver or large engraver will not trigger a recipe, even if it has been drained of all power. Discharged lapotron crystals also do not stack with freshly crafted crystals.

`/nbtedit` shows that even after being discharged, the charge NBT tag remains present:
- **Freshly crafted:** `{id:"gregtech:meta_item_1",Count:1,Damage:742s}`
- **Charged and discharged:** `{id:"gregtech:meta_item_1",Count:1,Damage:742s,tag:{Charge:0L}}`

Removing this tag with `/nbtedit` causes the recipe/stacking to work properly.

**Expected Behavior:** Empty lapotron crystals should stack with each other regardless of whether they have been charged previously, and should be recognised as the same item for recipes that need them.

**Steps To Reproduce:** Craft a lapotron crystal, charge it and then discharge it using machines or battery buffers, and attempt to place it in a laser engraver with a blue lens. The engraver will not start the lapotron crystal chip recipe.

Alternately, craft two lapotron crystals. Charge and discharge one, and they will no longer stack.

**Comment by IntegerLimit** [comment]
Can you transfer this issue to the GTCEu GitHub instead?

**Comment by fishsicles** [comment]
> Can you transfer this issue to the GTCEu GitHub instead?

Done; I wasn't initially sure if this was a Nomi recipe change or a GTCEu thing, so I posted it here first.

**Comment by IntegerLimit** [comment]
Thanks!
