### ISSUE TITLE
Machines integrated circuits randomly change nbt making them useless 

### ISSUE THREAD

**Issue by tTheEddie** [tracer4b/nomi-ceu#220]
Pack Version:
version was 1.5

Description:
randomly some machines weren't working and after looking around for the cause it turned out to be that the integrated circuits changed their nbt compared to normal ones 

Expected Behavior:
it should just make the machines work and change their number 

Steps To Reproduce:
sadly i couldn't do anything to reproduce the bug it just happened randomly i can't really tell how it happened but it just... did 

Crash Log:
game didn't crashed 

![image](https://user-images.githubusercontent.com/123299121/213967915-ef895f6b-cf72-4919-aa65-c268fdf64524.png)
this image shows the corrupted integrated circuits nbt

due to the lack of information in how to reproduce the bug i apologize for not being helpful

**Comment by IntegerLimit** [comment]
This is a GTCEu issue, has been reported to the GitHub, hopefully will be fixed next update.

**Comment by IntegerLimit** [comment]
https://github.com/GregTechCEu/GregTech/pull/1444 This will fix it.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/tracer4b/nomi-ceu/commit/3cc787ffb8fa7b6ac262e836c06f6c84c0f78359.
