### ISSUE TITLE
Crash at 4-5th stage of loading

### ISSUE THREAD

**Issue by Sequaren** [tracer4b/nomi-ceu#221]
**Pack Version:**
1.5.0
No changes have been made to the modpack.

**Description:**
This issue is almost a complete copy of this one - https://github.com/tracer4b/nomi-ceu/issues/183.
Can't run this modpack. Approximately at the beginning of the 5th stage of loading, a crash occurs. 
This happens both with the new version of Java (1.8.0_362) and with the old one (1.8.0_202).
At the same time, this modpack starts without problems - https://www.curseforge.com/minecraft/modpacks/nomifactory.

Based on the "original" issue i think that problem may be somewhere in the operating system.
My system is manjaro linux (more details in crash report).

**Expected Behavior:**
Loading minecraft completely.

**Steps To Reproduce:**
1. Downloading clean version of modpack.
2. Launching it from minecraft launcher.
3. Waiting until stage 4 of loading starts.
4. Getting crash at around the beginning of loading stage 5.

**Crash Log:**
Crash report https://mclo.gs/flxP5wA

**Screenshots:**
![MinecraftError1](https://user-images.githubusercontent.com/115504196/214142530-5e5087cc-f7a9-4057-9733-15354cabc215.jpg)

**Comment by tracer4b** [comment]
It seems like a faulty install. Did you use the CF launcher? Try installing with another launcher.

Try replacing the NC config file with the one under `overrides/config/nuclearcraft.cfg`.

**Comment by Sequaren** [comment]
CF itself is not available on linux, so I used curseforge cli - https://github.com/North-West-Wind/CurseForge-CLI. However, as I already wrote, dev nomifactory starts without problems. In general, this modpack is the first one that I had problems with.
Perhaps it is important to say that after the installation I still have the file nomi-ceu-client-1.5.zip. I extracted everything that was in it into modpack files. After the config files were overwritten (including nuclearcraft.cfg), I launched minecraft and they were immediately overwritten to the previous version. Then the crash happened again.

**Comment by Sequaren** [comment]
This helped https://github.com/GregTechCEu/GregTech/issues/1169
The problem was temporarily solved when I changed the nuclearcraft config.
I changed this
`# If enabled, recipes of the corresponding NC machine will also be added for GTCE machines. Order: Manufactory, Isotope Separator, Decay Hastener, Fuel Reprocessor, Alloy Furnace, Fluid Infuser, Melter, Supercooler, Electrolyzer, Neutron Irradiator, Ingot Former, Pressurizer, Chemical Reactor, Salt Mixer, Crystallizer, Fluid Enricher, Fluid Extractor, Centrifuge, Rock Crusher.
    B:gtce_recipe_integration <
        false
        true
        true
        true
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
     >`
     to this
     `# If enabled, recipes of the corresponding NC machine will also be added for GTCE machines. Order: Manufactory, Isotope Separator, Decay Hastener, Fuel Reprocessor, Alloy Furnace, Fluid Infuser, Melter, Supercooler, Electrolyzer, Neutron Irradiator, Ingot Former, Pressurizer, Chemical Reactor, Salt Mixer, Crystallizer, Fluid Enricher, Fluid Extractor, Centrifuge, Rock Crusher.
    B:gtce_recipe_integration <
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
        false
     >`
     However, I still got this error when entering the world. But the crash didn't happen.
     
![image](https://user-images.githubusercontent.com/115504196/214283290-c0cfbdbc-f1f2-4c3f-b6c7-7b65ad654fcf.png)

**Comment by IntegerLimit** [comment]
That would break NC fission, as it would disable the transfer of recipes needed for NC fission, such as fuel reprocessing.

**Comment by tracer4b** [comment]
This seems like an issue with CEu, I'll forward it.
Can you send the error log received with that message?

**Comment by ghzdude** [comment]
I believe this issue is purely on NC's side, as GTCEu's recipe system has changed drastically from GTCE's recipe system. The NC fuel reprocessing steps should be added back manually as a CraftTweaker script. Also, regarding the CraftTweaker error experienced, please upload the latest crafttweaker.log here, please.

**Comment by Sequaren** [comment]
Crafttweaker, latest and debug logs
[crafttweaker.log](https://github.com/tracer4b/nomi-ceu/files/10496982/crafttweaker.log)
[latest.log](https://github.com/tracer4b/nomi-ceu/files/10496983/latest.log)
[debug.log](https://github.com/tracer4b/nomi-ceu/files/10496984/debug.log)

**Comment by Sequaren** [comment]
I played on my server for some time and when I laid out the rubber plate recipe that was in HEI (hammer and two rubber mass) this rubber plate did not appear.
Now i have this error when i try to launch minecraft.
![image](https://user-images.githubusercontent.com/115504196/215277121-f28b1422-18a1-4abf-a9c0-fec6d1c0100d.png)

Crash report
https://mclo.gs/NRHVh3D

**Comment by IntegerLimit** [comment]
Try using a different launcher. For example, Prism Launcher. There are other launchers that work on linux.

**Comment by IntegerLimit** [comment]
Also, try turning off your Antiviruses, VPNs or Firewalls. It seemed to work for this issue: #243.

**Comment by IntegerLimit** [comment]
Does this happen in 1.5.1? Also, does this happen with the above suggestions implemented?

**Comment by TheAirBlow** [comment]
> I played on my dedicated server for some time and when i laid out the rubber plate recipe that was in HEI (hammer and two sticky resin) this rubber plate did not appear. I later tried to restart the game, but it crashed Now i have this error when i try to launch minecraft. ![image](https://user-images.githubusercontent.com/115504196/215277121-f28b1422-18a1-4abf-a9c0-fec6d1c0100d.png) Crash report https://mclo.gs/NRHVh3D
> 
> **After restarting the computer, minecraft at least loaded** but still tat rubber plate recipe does not work

Such weird crashes personally scream an unsupported JVM for me. OpenJDK or OpenJ9 should work perfectly - the second being thr most performant one, and the first one is the most compatible.

**Comment by IntegerLimit** [comment]
This usually happens due to the Curseforge Launcher. Thanks for the insight.

**Comment by TheAirBlow** [comment]
> This usually happens due to the Curseforge Launcher. Thanks for the insight.

The logs clearly state that he uses Linux, and I think he said so here before. Curse launcher on Linux supports only World of Warcraft.

**Comment by TheAirBlow** [comment]
> Also, try turning off your Antiviruses, VPNs or Firewalls. It seemed to work for this issue: #243.

Firewalls and VPNs are related to networking, which is irrelevant to any crashes that happened to him. Linux software usually doesn't operate like rootkits (kernel drivers) unlike most Windows anti-malware or VPN software.

Antiviruses? No way a Linux user is going to use any, and also there's only one - ClamAV. If someone is using Linux in the first place, they don't need any anti-malware running on their system, just because Linux is a lot more secure out of the box, and everyone in the community will mock you for running random shit you download off internet as root :P (as admin in windows), and this is more than enough to keep yourself safe, as the default configs are as secure as possible.

**Comment by IntegerLimit** [comment]
> CF itself on linux is only for WoW, so I used curseforge cli - https://github.com/North-West-Wind/CurseForge-CLI. However, as I already wrote, dev nomifactory starts without problems. In general, this modpack is the first one that I had problems with. Perhaps it is important to say that after the installation I still have the file nomi-ceu-client-1.5.zip (same for dev version). I extracted everything that was in it into modpack files. After the config files were overwritten (including nuclearcraft.cfg), I launched minecraft and then that files was immediately overwritten to the previous version (same happened when i changed only nuclearcraft config on that from archive). After reaching 4-5 stage of loading the crash happened again.

Might be related. Thank you for this insight. Do you experience this crash?

**Comment by IntegerLimit** [comment]
It seems that it might be related, as Curseforge CLI still uses the Vanilla Launcher.

**Comment by TheAirBlow** [comment]
> It seems that it might be related, as Curseforge CLI still uses the Vanilla Launcher.

Yeah. @Sequaren, you should try using Prism Launcher with OpenJDK or OpenJ9 (compatibility/performance, but both work well with this modpack, the only problem I experienced with J9 is that Recurrent Complex crashes with it due it being unmaintaned and old)

**Comment by IntegerLimit** [comment]
@TheAirBlow Do you experience this crash? I assume you are using linux.

**Comment by TheAirBlow** [comment]
> @TheAirBlow Do you experience this crash? I assume you are using linux.

I didn't, but I remember weird java crashes that looked similar to this

**Comment by IntegerLimit** [comment]
Closing issue, as it seems to be a problem with the launcher, or with their java install.
