### ISSUE TITLE
Vanilla diamond sword and Gregtech diamond file have the exact same recipe

### ISSUE THREAD

**Issue by LemurVladimir** [tracer4b/nomi-ceu#227]
Version: 1.5.0

As per title, vanilla Diamond Sword is uncraftable due to its modified recipe (2x diamond plates + 1x stick) being the same as a Gregtech Diamond File. 
This doesn't render a diamond sword unobtainable if played on any difficulty besides Peaceful as it's still available through villager trading. On Peaceful though this makes things like Dark Utilities' Diamond Spikes or Draconic Evolution's Upgrade Key (Attack AOE) unobtainable.

**Comment by IntegerLimit** [comment]
Fixed in https://github.com/tracer4b/nomi-ceu/commit/12393dbd8530f7894f0334b1ef11fb676d653514.
