### ISSUE TITLE
STE Genesis quest doesn't unblock primitive blast furnace

### ISSUE THREAD

**Issue by kevintok** [tracer4b/nomi-ceu#228]
![2023-01-27_00 05 10](https://user-images.githubusercontent.com/3733705/215038167-0daed2b6-2788-4c6f-8866-30e8122cae4e.png)
![2023-01-27_00 05 15](https://user-images.githubusercontent.com/3733705/215038171-6ed74ec6-d236-4f36-8ef5-c9d266cf961d.png)
Playing on 1.5 with hard mode on a server

**Comment by IntegerLimit** [comment]
Do /bq_admin edit false.
