### ISSUE TITLE
Hamburger Recipe produces Bio-Mash instead

### ISSUE THREAD

**Issue by jd-ihm** [tracer4b/nomi-ceu#229]
**Pack Version:**
1.50

**Description:**
Hamburger Recipe produces Bio-Mash from actually additions instead.

**Expected Behavior:**
Hamburger Recipe should produce a hamburger.

**Steps To Reproduce:**
Place the required ingredients in a crafting table.

**Crash Log:**
No Crashes

**Screenshots:**
![image](https://user-images.githubusercontent.com/44578358/215241609-7c7891b2-f9ae-4fbe-a22d-71e8bdd769e1.png)

**Comment by IntegerLimit** [comment]
This is leaving me confused. This is probably Actually Additions's fault, and Bio-Mash has no recipes in JEI, so I'm not sure on how to remove it.

**Comment by jd-ihm** [comment]
I suspect it has to do with the actually additions knife

**Comment by jd-ihm** [comment]
https://github.com/DarkPacks/SevTech-Ages/issues/4070 this is indeed an actually additions issue.

The work around for this is to put the Actually Additions Knife in last and it will give the correct recipe.
Closing this @IntegerLimit .

**Comment by IntegerLimit** [comment]
Thanks.
