### ISSUE TITLE
Rubber Plates uncraftable earlygame

### ISSUE THREAD

**Issue by HermitForge** [tracer4b/nomi-ceu#231]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5 Curseforge

**Description:**
when attempting to craft rubber plates early game, the crafting recipe just doesn't work

**Expected Behavior:**
they should be craftable

**Steps To Reproduce:**
use a crafting table or a crafting station, take a hammer, and do the recipe for rubber plates

**Crash Log:**
did not crash, did not give an error

**Screenshots:**
![2023-01-27_22 32 28](https://user-images.githubusercontent.com/59539607/215278715-48e7c5fd-2445-4f2c-9d76-b94b1deb06b0.png)
![2023-01-27_22 32 33](https://user-images.githubusercontent.com/59539607/215278723-29514ac5-3f9e-44b8-a333-ce95774bbbb6.png)
![2023-01-27_22 32 54](https://user-images.githubusercontent.com/59539607/215278724-d84f80f3-ba68-40c1-b727-dc478f3c606b.png)
![2023-01-27_22 33 02](https://user-images.githubusercontent.com/59539607/215278727-f7e8ced5-377f-4fb2-9ee0-3d131085aeb1.png)
![2023-01-27_22 33 18](https://user-images.githubusercontent.com/59539607/215278734-d50d4fa9-a599-4277-b6ff-e13be6a40d53.png)
![2023-01-27_22 32 30](https://user-images.githubusercontent.com/59539607/215278718-666626da-6845-4a4d-ae56-65b99b21b2e3.png)

**Comment by IntegerLimit** [comment]
Fixed. View the pinned message in the channel on discord, or the message at the very bottom of the pinned issue on GitHub to find how to fix it.
