### ISSUE TITLE
Quest for "dark soularium" in end game tab requires tritanium coils instead of trinium

### ISSUE THREAD

**Issue by GiuGii** [tracer4b/nomi-ceu#232]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5, no additional mods

**Description:**
title is enough description

**Expected Behavior:**
dark soularium ingot quest should require trinium and not tritanium coils

**Steps To Reproduce:**
open quest book 
use eyes 

**Crash Log:**
no

**Screenshots:**
![image](https://user-images.githubusercontent.com/123425104/215298445-80675ad2-2f76-4f60-af06-b27245fe86ef.png)
![image](https://user-images.githubusercontent.com/123425104/215298454-157b3072-4203-42d1-9cc9-ad9e3a671dc6.png)

**Comment by IntegerLimit** [comment]
Working on it.
