### ISSUE TITLE
Quest book not loading any quests when hosting a server.

### ISSUE THREAD

**Issue by WAYVE1** [tracer4b/nomi-ceu#234]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
nomi-cue-client-1.5
nomi-ceu-server-1.5
**Description:**
When hosting a server using nomi-ceu-server-1.5 downloaded from the cursedforge client, the quests do not load, i have tried using bq_admin edit and bq_admin default load but both commands arent found. ive loaded a singleplayer world and the quests show up, but when i connect to the server im hosting using local host no quests pop up in the better questing book.

**Expected Behavior:**
when loading the world and opening the quest book, all quests and quest catagories would show.

**Steps To Reproduce:**
download the server client from cursed forge, go through the steps of running the server, open nomifactory 1.5 and connect to server with localhost and open the quest book with the assigned key, no quests will pop up when  going into the quest tab.

**Screenshots:**
![image](https://user-images.githubusercontent.com/123905078/215357336-737dfcd1-571f-4192-9aa0-04d89c81f6d4.png)

**Comment by IntegerLimit** [comment]
What client are you using? The curseforge one h@s been reported to have problems with launching modpacks.

**Comment by WAYVE1** [comment]
> What launcher are you using? The curseforge one has been reported to have problems with launching modpacks.

yes im using the cursedforge, i downloaded the server pack from the cursed forge launcher as well

**Comment by IntegerLimit** [comment]
Try using a different launcher.

**Comment by WAYVE1** [comment]
> Try using a different launcher.

Any recommendations? I’ve only really used cursed forge for mod packs and hosting servers

**Comment by IntegerLimit** [comment]
I personally use Prism Launcher. It's pretty good.

**Comment by IntegerLimit** [comment]
@WAYVE1 Did using a different launcher fix the problem?

**Comment by IntegerLimit** [comment]
It should fix the problem. If the problem still occurs using a different launcher, and `/bq_admin default load` and then `/bq_admin edit false` didn't fix it, please re-open this issue.
