### ISSUE TITLE
Autoclave Recipes that can use distilled water for faster processing / guaranteed drop default to water in the large autoclave chamber

### ISSUE THREAD

**Issue by hobnob11** [tracer4b/nomi-ceu#235]
**Pack Version:**
1.5.0

**Description:**
I'm trying to use the Gregicality Large Autoclave Chamber to replace my many different autoclaves with a single multiblock that has some nonuple fluid inputs and every fluid. 
For polished stone, I need to have water in the multiblock. 
For most other recipes, I need distilled water to guarantee a drop like certus quartz. 
Because I have both liquids, and theres no way to tell it which to use, trying to make certus quartz fails because it defaults to using the water instead of the distilled. 

**Expected Behavior:**
Ideally, recipes that can use multiple fluids would use a circuit to let you specify which fluid to use like most other processing machines. 

**Steps To Reproduce:**
1. Gregicality Large Autoclave Chamber
2. Supply it with both Water and Distilled Water. 
3. Try and craft Certus Quartz from the dust, it uses the Water not the Distilled water.

**Comment by IntegerLimit** [comment]
This is a GTCEu issue. Is Polished Stone the only recipe that can't use Distilled Water instead of Water? I could simply add a Polished Stone recipe using Distilled Water.

**Comment by hobnob11** [comment]
from what I can find: 
- Polished Stone
- Black Quartz
- Clay
I think these are all of the recipes that cannot be made with distilled.

**Comment by IntegerLimit** [comment]
Thanks.

**Comment by IntegerLimit** [comment]
Clay Autoclaving not having Distilled Water recipe is GTCEu issue. Reported, see above message.

**Comment by IntegerLimit** [comment]
Added Distilled Water recipes for Polished Stone and Black Quartz.

**Comment by IntegerLimit** [comment]
Clay recipe will have to wait until https://github.com/GregTechCEu/GregTech/issues/1469 is fixed.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/tracer4b/nomi-ceu/commit/3cc787ffb8fa7b6ac262e836c06f6c84c0f78359.
