### ISSUE TITLE
Certus Quartz Dust from AE2 UEL cant be used

### ISSUE THREAD

**Issue by Americangerman1** [tracer4b/nomi-ceu#236]
You can find the dust in mineshaft chests and it gives a good amount with luck. 
When using JEI, you cant search for it, you have to physically have it to look it up. The only thing you get is that it comes from the mineshaft chests and nothing can be made or converted from it. 

Can you add it to the ore dictionary so that it can be used for making the seeds?

**Comment by IntegerLimit** [comment]
Closed with ce18dbe46019b78a3d65d7e56663762e8def4490.
