### ISSUE TITLE
Crafting Station Inventory Tab hides 9th row making some items inaccessible

### ISSUE THREAD

**Issue by mateskr692** [tracer4b/nomi-ceu#237]
**Pack Version:**
1.5

**Description:**
When going to Crafting Station conncected inventories tab, some items are hidden and inaccessible even if they are in connected inventories and in the crafting tab you can them as available. I believe this is happening because Inventory tab only shows 8 columns of items and instead of wrapping the last column, it hides them behind the GUI so you cant retrieve them,

**Expected Behavior:**
All items in connected inventories should be accessible through the Connected Inventories tab rather than some being missing.

**Steps To Reproduce:**
Place a crafting station next to a chest and put 8 different items in the chest. They are all visible in the crafting station. Now put the 9th, different item and it doesnt show in the inventory tab

**Screenshots:**
![image](https://user-images.githubusercontent.com/32541962/216736668-08e00cb6-31a7-4709-843f-62c6b082e801.png)
In the first screenshot both Iron and Gold ingots are accesible. Putting in the Lilac flower pushes the gold of of bounds making it unavailable
![image](https://user-images.githubusercontent.com/32541962/216736728-ec17a40d-73c3-4239-8d64-c34ca8d280bf.png)
Putting in the apples, pushes the Iron out of bounds and makes the gold show back in the new row
![image](https://user-images.githubusercontent.com/32541962/216736789-c410e216-af2e-45a2-8e8c-ef50d778b1a4.png)

**Comment by IntegerLimit** [comment]
Report to GTCEu.

**Comment by IntegerLimit** [comment]
Thanks for transferring it to the GTCEu Github.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/tracer4b/nomi-ceu/commit/3cc787ffb8fa7b6ac262e836c06f6c84c0f78359.
