### ISSUE TITLE
Enlightened and Dark Fused Quartz and Fused Glass recipes are not working

### ISSUE THREAD

**Issue by Caerglad** [tracer4b/nomi-ceu#240]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5.0

**Description:**
When adding Enlightened Fused Quartz ingridients (as in JEI) to alloy smelter nothing happens

**Expected Behavior:**
Recipe should run

**Steps To Reproduce:**
Add fused quartz and glowstone to alloy smelter (LV+)

**Screenshots:**

![image](https://user-images.githubusercontent.com/1807505/217191806-e094f9b6-8aba-49b4-8f1e-ff93dc5b84a2.png)

**Comment by IntegerLimit** [comment]
Confirmed.

**Comment by IntegerLimit** [comment]
Fix has been implemented on my local, push to main soon, after I do a couple more changes.
