### ISSUE TITLE
Custom Alloy Smelter Alloys in Alloy Blast Smelter

### ISSUE THREAD

**Issue by Correlander** [tracer4b/nomi-ceu#242]
Not a bug report, just suggestion, sorry if this isn't where they are intended to go. Just was wondering why invar can't be made in ABS? Seems like it should be added to it for consistency, as most others that are made in mixer can be alternatively made in ABS?

**Comment by IntegerLimit** [comment]
Invar belongs to the rest of the Alloy Smelter recipes, such as Electrum and Conductive Iron. If these were to be added, it would be very hard, and it would have to be implemented by GCYM first, for things like Invar, Steel and Electrum, before we add other recipes like Conductive Iron, Dark Steel or End Steel.

**Comment by IntegerLimit** [comment]
Oops, closed as completed instead of not intended.

**Comment by Correlander** [comment]
Ah, I was looking at its recipe where you mix invar dust, then smelt it, which led me to that conclusion. Didn't realize it was also an alloy smelter recipe. Makes sense now.

**Comment by IntegerLimit** [comment]
This is now relevant, due to GCYM adding ABS recipes for various Alloy Smelter recipes. Probably not invar tho.

**Comment by IntegerLimit** [comment]
Conductive Iron, Dark Steel and End Steel is the current list, but there might be more.

**Comment by IntegerLimit** [comment]
Closed with https://github.com/tracer4b/nomi-ceu/commit/1eaa95b33f1db08105bf625691dcf347a78a1903.
