### ISSUE TITLE
Default World Generator - World Creation Crash

### ISSUE THREAD

**Issue by Zanadarn** [tracer4b/nomi-ceu#243]
![image](https://user-images.githubusercontent.com/124720628/217341733-00b5ed1e-8e84-4faa-bba0-ac4e96bbd0c0.png)

Crash report:
https://mclo.gs/6viCFpe

Attempted fixes:
Reinstalled Java (jre-8u361)
Switched from CF to Prism Launcher
Uninstalled Avast (read some people had had issues with it and world gen)

Please help, I'm out of troubleshooting ideas.

**Comment by IntegerLimit** [comment]
No idea. Is Default World Generator in the pack?

**Comment by Zanadarn** [comment]
DefaultWorldGenerator-port-1.12-2.3.1 apparently

**Comment by IntegerLimit** [comment]
I have no idea, but you could try reporting to defaultWorldGenerator's GitHub.

**Comment by Zanadarn** [comment]
Yes, I even switched launchers to see if that was somehow the issue.

**Comment by Zanadarn** [comment]
The (really dumb) answer for anyone stumbling onto this post through the internet looking for a solution. Apparently antiviruses and firewalls are known to cause issues with 1.12.2, it's not modpack specific (outside of the fact that many modpacks are on that version). I thought I'd ruled that out during my troubleshooting session. 

I forgot one thing. VPN's can also have similar sorts of software baked in. Turning off the VPN fixed the issue.

**Comment by hron84** [comment]
What's the exact problem of firewalls/AVs with 1.12.2?

**Comment by IntegerLimit** [comment]
No idea. I guess, just turn off your AVs, firewalls or VPNs when having trouble with launching the modpack.
