### ISSUE TITLE
Unable to craft small piles of various dusts from large pile

### ISSUE THREAD

**Issue by J-Dill** [tracer4b/nomi-ceu#245]
**Pack Version:**
1.5

**Description:**
Looking through HEI for various dusts, it says that you should be able to craft the _small_ piles for the various dusts in the game. After doing so in both a vanilla crafting table and a Crafting Station, it will only yield tiny piles.

**Expected Behavior:**
When a dust with a small recipe is placed in the top-middle square in a crafting grid, it should yield 4 small piles. Currently, it will give 9 tiny piles.

**Steps To Reproduce:**
Same as expected behavior.

**Crash Log:**
N/A

**Screenshots:**
Graphite Dust:
![image](https://user-images.githubusercontent.com/35313950/217687565-44612365-3571-4561-ad74-d4112e62db29.png)
Aluminium Dust:
![image](https://user-images.githubusercontent.com/35313950/217687879-a523f3ab-ea53-4488-b752-353371529634.png)

**Comment by Folanlron** [comment]
Move the dust over 1 spot and it will be small...

**Comment by IntegerLimit** [comment]
Yeah, JEI preview is wrong. If you wanted those fixed, try reporting to https://github.com/GregTechCEu/GregTech/issues.
