### ISSUE TITLE
draconium meteorite and multi smelter progression skip

### ISSUE THREAD

**Issue by Tralomine** [tracer4b/nomi-ceu#25]
**Pack Version:**
1.1.2

**Description:**
end meteorites gives draconic evolution's draconium dust, which can only be smelted into draconic evolution's draconium ingots, which are useless, unless you melt them in a steam oven or multi smelter in which case you get gregtech's draconium ingots, which allow some progression skip

**Expected Behavior:**
either the ores on meteorites should be gregtech's draconium ore, or the dust shouldn't be able to be smelt into ingots

notes: I don't know if it's due to auto recipes by gtceu or not, that's why I'm reporting it here, if it's not please tell me so that I can report it to the regular nomifactory/omnifactory projects

**Comment by tracer4b** [comment]
End meteorites were disabled in version 1.1.3
