### ISSUE TITLE
Several circuit boards cannot be made.

### ISSUE THREAD

**Issue by pbwind** [tracer4b/nomi-ceu#252]
**Package version:**
1.5 Server version

**Description:**
The circuit board cannot be made.
Including: workstation, mainframe, Nano Supercomputer
I have made workstation and mainframe when upgrading to the latest version, and there is no problem.
At present, it may be that the formula of the circuit board has been changed, which makes it impossible to make.

**Expected behavior:**
1. The task cannot continue
2. Can't go on

**Reproduction steps:**
The above three or more formulations may be different from the previous version,
It can be made before.
The latest version cannot be made.

**Screenshot:**
![hecheng-02](https://user-images.githubusercontent.com/9552704/218899695-e61c27f7-1522-465a-9dac-7e65d137dda9.png)
![hecheng](https://user-images.githubusercontent.com/9552704/218899712-5e915390-6f13-4166-b4c8-3558ecd8633b.png)
![gongzuo](https://user-images.githubusercontent.com/9552704/218899733-d5dda63a-9444-429a-8c78-b53d4b2688da.png)
![gongzuo-02](https://user-images.githubusercontent.com/9552704/218899738-449d5375-fabf-4cec-ba9f-617bafff1a44.png)

**Comment by pbwind** [comment]
Scripts affect recipes.  question closed

**Comment by IntegerLimit** [comment]
? So does it work?

**Comment by IntegerLimit** [comment]
Does this happen in 1.5.1?

**Comment by pbwind** [comment]
> 这会发生在 1.5.1 中吗？

The occurring version is 1.5.0.
I haven't updated my server version to 1.5.1.
At present, my countermeasure is to use the Sinicization of the task book alone.

What do you need me to do.

**Comment by Brittank88** [comment]
> I haven't updated my server version to 1.5.1.

Just jumping in to say I couldn't even figure out how to update my server to 1.5.1, as no server zip was present in the 1.5.1 release. Would love to know how it's even possible to update.

**Comment by IntegerLimit** [comment]
> > I haven't updated my server version to 1.5.1.
> 
> Just jumping in to say I couldn't even figure out how to update my server to 1.5.1, as no server zip was present in the 1.5.1 release. Would love to know how it's even possible to update.

Nope, its on purpose, there are problems with MBT and multiplayer on newest.

**Comment by IntegerLimit** [comment]
Also, @pbwind, it seems you are using Diodes. Does the recipe accept Diodes, or only SMD Diodes?

**Comment by IntegerLimit** [comment]
It seems the recipe only accepts SMDs, and not normal Diodes. Closing for now.
