### ISSUE TITLE
DeepMobEvolution Tooltip error causing crashes

### ISSUE THREAD

**Issue by Shay-1** [tracer4b/nomi-ceu#254]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**

v1.5

**Launcher:** 

Prism Launcher - portalble zip

**Description:**

The mob modules from DeepMobEvolution have a tooltip error when looking at them in Jei. However when trying to craft one or trying to interact with an existing module. The game will crash upon hovering your mouse over the module

**Expected Behavior:**

Display working tooltip without causing game to crash 

**Steps To Reproduce:**

Try and craft a mob module, any of them, it will crash as soon as you hover mouse over it

**Screenshots**

![Screenshot (103)](https://user-images.githubusercontent.com/125572771/219382810-2bcefb7f-aa13-42a8-87e2-49d435a1968e.png)
![Screenshot (104)](https://user-images.githubusercontent.com/125572771/219382813-7882105a-bcdf-4613-b134-230a8f6a153c.png)
![Screenshot (105)](https://user-images.githubusercontent.com/125572771/219382818-d08d6654-254b-4bba-9c83-135f9cc243f3.png)

**Crash report**

[crash-2023-02-16_13.47.42-client.txt](https://github.com/tracer4b/nomi-ceu/files/10756627/crash-2023-02-16_13.47.42-client.txt)

**Comment by Shay-1** [comment]
Just realised that this seems to be the same problem as the turbines tooltip which has been dealt with already

**Comment by IntegerLimit** [comment]
It's probably different. That issue was only related to GTCEu Turbines, due to the Tool Rework. I'll have a look at it, maybe report to DME?

**Comment by IntegerLimit** [comment]
This isn't happening for me.

**Comment by Shay-1** [comment]
Problem has been resolved. The issue was caused by my addition of betterFps mod into the pack
