### ISSUE TITLE
New Wireless crafting terminal replaces whatever is in your hand when hotkeyed as a bauble

### ISSUE THREAD

**Issue by albus522** [tracer4b/nomi-ceu#257]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**

Check if the bug is fixed on the latest version before submitting. The latest version is v1.5.1.

v1.5.1

**Launcher:**

CurseForge Launcher

**Mode:**

Normal Mode (but probably both Modes).

**Description:**

If you have the new wireless crafting terminal equipped as a bauble and are using a hotkey, when you close the terminal, whatever was in your hand will now be another copy of the terminal voiding whatever was in your hand.

**Expected Behavior:**

The wireless crafting terminal should work as a bauble given the guide suggests it.

**Steps To Reproduce:**

Setup a hotkey to open the wireless crafting table.
Put the wireless crafting terminal in a bauble slot.
Activate the wireless crafting terminal via hotkey.

**Comment by IntegerLimit** [comment]
Please report to https://github.com/PrototypeTrousers/Applied-Energistics-2/issues.

**Comment by Caedis** [comment]
Unable to reproduce
