### ISSUE TITLE
After updating got registry error

### ISSUE THREAD

**Issue by hdks1111** [tracer4b/nomi-ceu#259]
After updating nomifactory-ceu I got a error.[](url)
![Screenshot 2023-02-18 102210](https://user-images.githubusercontent.com/125722677/219844805-61cbecae-4b46-4a0a-90e5-1e4281d6cabb.png)

**Comment by Folanlron** [comment]
Items that do not actually exist being removed is all that is, perfectly normal..

**Comment by IntegerLimit** [comment]
Perfectly normal. Just press Ok. I just removed some useless un-obtainable stuff.
