### ISSUE TITLE
Crafting Station doesn't show amount of crafted items

### ISSUE THREAD

**Issue by DeForce** [tracer4b/nomi-ceu#260]
**Pack Version:** v1.5.1.
**Launcher:** PolyMC
**Mode:** Normal Mode
**Description:**

When I craft items in crafting station I don't understand how many I have crafted.
Video: https://user-images.githubusercontent.com/7394420/219851875-6bcfea39-6a5e-4002-a047-724b8a4ee44a.mp4

**Expected Behavior:**
I see the amount of items in my hand.

**Steps To Reproduce:**
Open Crafting station, select recipe, click the recipe multiple times - see that no "number of items" is added at the bottom of the item

**Comment by IntegerLimit** [comment]
Known issue. This happens with all GT GUIs. Should be fixed by https://github.com/GregTechCEu/GregTech/pull/1502.

**Comment by IntegerLimit** [comment]
Fixed in next GTCEu update (whenever that comes)
