### ISSUE TITLE
energy converter won't convert RF to EU

### ISSUE THREAD

**Issue by AndIOoF** [tracer4b/nomi-ceu#261]
Pack Version:
1.5.1

Launcher:
CurseForge Launcher

Mode:
Normal mode

Description:
the energy converters won't convert RF to EU, power does not travel through wires to other machines. tested with various tiers of voltage, void/overworld, as well as in a different world, the converters still wouldn't convert. i also tested through the PolyMC launcher and it works there

Expected Behavior:
machines connected through wires should receive EU and RF in dynamos should decrease

Steps To Reproduce:
i don't know how this bug came to be, but i was playing on an online server with my friend when the machines suddenly stopped receiving power. 

Crash Log:
i'm pretty sure this didn't come from the game crashing, but there is a crash log around the time when the bug appeared
[crash-2023-02-17_20.27.43-client.txt](https://github.com/tracer4b/nomi-ceu/files/10775107/crash-2023-02-17_20.27.43-client.txt)

Screenshots:
https://youtu.be/ywkUBuT5Scs this is what it looks like ingame

**Comment by LordofDorknes** [comment]
In the video you posted, it looks like the output face of the energy converter is facing upward, and not toward the wire you want to output to. Try using a gregtech wrench to rotate the energy converter output side to the block with the wire.
