### ISSUE TITLE
CraftTweaker issue: Microverse Projector Disappears on update, Not craftable

### ISSUE THREAD

**Issue by LordofDorknes** [tracer4b/nomi-ceu#262]
**Pack Version:** 1.5.1
**Launcher:** Curseforge
**Mode:** Normal
**Description:**
Likely closely related to issue #255:

After updating a world from v1.5 to 1.5.1, microverse controller and advanced microverse controller disappeared from the world. 

The player is unable to craft any of the three types of microverse projector - the recipes simply do not work.
Additionally, attempts to spawn in the microverse projectors shown in hei do not work as the server does not recognize any items that being with "crafttweaker:" such as "crafttweaker:microverse_projector_basic"

**Expected Behavior:**
Microverse projector should not disappear on version change, microverse projector should remain craftable in v1.5.1

**Steps To Reproduce:**

Place microverse projector in v1.5 save, then load it in 1.5.1 server. Additionally, attempt to craft any microverse projector in 1.5.1. 

**Crash Log:**
 I am not certain if this crash log is related to the microverse projector, but it was an unexpected crash log generated because of crafttweaker on updating the server version, so it may be related.

[crash-2023-02-17_15.26.47-server.txt](https://github.com/tracer4b/nomi-ceu/files/10775157/crash-2023-02-17_15.26.47-server.txt)

Additionally, here is a crafttweaker.log from the server, which likely contains the more relevant information:
[crafttweaker.log](https://github.com/tracer4b/nomi-ceu/files/10775167/crafttweaker.log)

The client-side crafttweaker log does not show the errors from the server one, so here it is for comparison:
[crafttweaker.log](https://github.com/tracer4b/nomi-ceu/files/10775170/crafttweaker.log)

**Screenshots:**
![2023-02-18_12 39 29](https://user-images.githubusercontent.com/2120489/219898318-6901149c-93ec-4e40-b82a-0a5b95cc2012.png)
![2023-02-18_12 39 41](https://user-images.githubusercontent.com/2120489/219898327-8c6fb737-202b-4cb4-a311-a8c68938e59c.png)
![2023-02-18_12 40 48](https://user-images.githubusercontent.com/2120489/219898330-55d2fb7b-b8c4-46d7-aa0a-c538fb7a69a3.png)
![2023-02-18_12 40 56](https://user-images.githubusercontent.com/2120489/219898335-a0cba483-ea72-4b70-a6e6-c985279a1a20.png)

**Comment by IntegerLimit** [comment]
Oh, so it happens to others too! We're waiting on a mbt patch to fix this.

**Comment by IntegerLimit** [comment]
Might be fixed with https://github.com/GregTechCEu/GregTech/pull/1541 or https://github.com/GregTechCEu/GregTech/pull/1544, or maybe both.
