### ISSUE TITLE
Pack crashes with appropriate version of spongeforge

### ISSUE THREAD

**Issue by Benedictum** [tracer4b/nomi-ceu#263]
**Pack Version: 
1.5.1

**Launcher:**
headless server

**Mode:**
hard mode configs

**Environment:**
linux dedicated headless server on shockbyte hosting, running forge 14.23.5.2860

**Description:**
Trying to setup a new server with spongeforge for moderation. Started up a forge headless server like normal to get forge installed, uploaded the contents of the modpack and rebooted, server loaded and world was present. Added spongeforge 1.12.2-2838-7.4.7 which is the "works with 2860" full release. on server boot get errors. Removing spongeforge no errors. Errors vary, first was a crafttweaker error, then one was for gregtech, and one was for advanced rocketry. Checking various config changes could not get it to move forward. Would like to run nucleus and luckperms with spongeforge but even just spongeforge errors and crashes.

**Expected Behavior:**
Should be able to launch headless server with spongeforge

 if matching forge version

**Steps To Reproduce:**
Setup server with 1.5.1 server pack and expert configs. See it boots normally. Add spongeforge 1.12.2-2838-7.4.7 latest recommended build to mod folder, boot, observe crashes.

**Crash Log:**
crash reports, latest.log, and crafttweaker logs
[crafttweaker.log](https://github.com/tracer4b/nomi-ceu/files/10822144/crafttweaker.log)
[crash-2023-02-23_06.09.03-server.txt](https://github.com/tracer4b/nomi-ceu/files/10822145/crash-2023-02-23_06.09.03-server.txt)
[latest.log](https://github.com/tracer4b/nomi-ceu/files/10822147/latest.log)

**Comment by IntegerLimit** [comment]
Same as https://github.com/tracer4b/nomi-ceu/issues/255. Wait for 1.5.2, as there are compat problems at the moment with GTCEu and MBT.
