### ISSUE TITLE
Recipe conflict for Blaze Powder conflicts with Hydrogen Sulfide and Tungsten Dust

### ISSUE THREAD

**Issue by felix-schneider** [tracer4b/nomi-ceu#266]
Not sure if those are recipes introduced by the pack or by GTCEu, so I'm opening here, but feel free to redirect me:

Blaze Powder: Carbon + Sulfur
Hydrogen Sulfide: Sulfur + Hydrogen
Tungsten Dust: Tungsten Trioxide + Hydrogen
Both are chem reactor recipes without a circuit. Inserting Sulfur + Carbon + Tungsten Trioxide + Hydrogen (needs LCR), wishing to make Blaze Powder and Tungsten Dust actually creates Hydrogen Sulfide and leaves the rest. One of those recipes should need a circuit.

**Comment by IntegerLimit** [comment]
Um, HM? I'll have a look at it.

**Comment by IntegerLimit** [comment]
Is this really a conflict? Two CRs/LCRs should be used instead to do this. one with Carbon + Sulfur, and one with Tungsten Trioxide +Hydrogen.

**Comment by felix-schneider** [comment]
Yes I guess LCRs have many of these conflicts, because they can have so many slots. I also made a bunch of HCl by accident. I guess this is more of a general LCR problem. Maybe the GTCEu devs could have a look at that and more aggressively use circuits to distinguish recipes.

**Comment by Folanlron** [comment]
The circuit # system is not to be used as a way to cheapen the amount of LCRs you require..

If that was the case we would have circuit numbers in the 50-80 range and it would be really annoying.

Nobody has issues, you can combine recipes in LCRs you just have to be smart about it..

**Comment by IntegerLimit** [comment]
If you really want a recipe revamp, please report to GTCEu instead. 

However, as Folanlron pointed out, it won't be too good of an idea, and furthermore, it'll break people's setups. I recommend you, like the QB says, use a LCR for each recipe, or combine recipes carefully.
