### ISSUE TITLE
Maybe add new roles for discord, currently we got the electronic types, but what if there is a hardmode version? like hm lv, hm mv, etc. It would help hardmode players to differentiate from their normal counterparts. 

### ISSUE THREAD

**Issue by altmines** [tracer4b/nomi-ceu#268]
Just some channel roles tbh, would help solve some confusion and is also a qol for the nomifactory discord.

**Comment by IntegerLimit** [comment]
Maybe better in https://discord.com/channels/927050775073534012/935070395751620658, as this isn't really for discord. Thank you for the idea. Ask exa, as he is the manager of the discord server.

**Comment by IntegerLimit** [comment]
Message tracer about it.
