### ISSUE TITLE
Stop sugarcanes from growing in spacestations

### ISSUE THREAD

**Issue by altmines** [tracer4b/nomi-ceu#269]
**Is your feature request related to a problem? Please describe.**
Sugarcanes are plants, they shouldnt be growable in a environment without air

**Describe the solution you'd like**
To prevent sugarcane from growing in the space /moon unless its in enclosed   spaces with air pockets

**Describe how the solution will work**
This would prevent players from growing sugarcane in the space, which is unrealistic. I know nomifactory isnt 100% irl stuff, but i think this would make sense, its like crops not growable in the nether for example, and water not placeable in the nether.

**Comment by TheAirBlow** [comment]
> I have no idea if this is possible, or how to do it, but I'm sure we could think about it if someone PRed.

You have to fork Advanced Rocketry for that :trollface: 
The mod itself is pain in the ass from the start, I've had multiple crashes with it in my custom modpack, and also you can't put any conduits in the multiblock detection bounds...

**Comment by TheAirBlow** [comment]
Bruh misclick

**Comment by TheAirBlow** [comment]
> Yeah, you could report to Adv Rocketry, tho I don't think their going to do anything about it. It was a cheery idea, but I'm sure we can't do this.

Yeah, it is abandoned. We should bring it up and make an LTS fork like AE2 extended life.
