### ISSUE TITLE
> I have no idea if this is possible, or how to do it, but I'm sure we could think about it if someone PRed.

### ISSUE THREAD

**Issue by TheAirBlow** [tracer4b/nomi-ceu#270]
> I have no idea if this is possible, or how to do it, but I'm sure we could think about it if someone PRed.

You have to fork Advanced Rocketry for that :trollface: 
The mod itself is pain in the ass from the start, I've had multiple crashes with it in my custom modpack, and also you can't put any conduits in the multiblock detection bounds...

_Originally posted by @TheAirBlow in https://github.com/tracer4b/nomi-ceu/issues/269#issuecomment-1453201684_

**Comment by IntegerLimit** [comment]
????

**Comment by TheAirBlow** [comment]
> ????

I said it is a misclick xdd
