### ISSUE TITLE
Wireless Crafting Terminal setting persistence

### ISSUE THREAD

**Issue by jameseck** [tracer4b/nomi-ceu#273]
Pack Version: 1.5.1

Launcher: gdlauncher

Mode: Normal

Environment: Singleplayer

Description: The Wireless Crafting Terminal bauble does not remember "Sort By".  Every time you open the terminal, the sort order defaults back to AZ.  This also applies to View and Sort Order.

Expected Behavior: The settings should persist between opening and closing the terminal.

**Comment by IntegerLimit** [comment]
Fixed in next update.
