### ISSUE TITLE
Aluminum Blocks and their chisel variants are inaccessible

### ISSUE THREAD

**Issue by JustBooom** [tracer4b/nomi-ceu#282]
Aluminum blocks are currently inaccessible in nomifactory ceu, because thermal foundation aluminum was disabled. I think it would be great if we could turn gregtech aluminium blocks into alumium with either chisel or some craft, for example aluminium block and a white dye (since thermal foundation aluminum blocks are white). aluminum chisel block looks really good and matches industrial style, so it would be great if we could get them in survival.

**Comment by IntegerLimit** [comment]
I am not sure if this is possible, but I will take a look.

**Comment by IntegerLimit** [comment]
Investigating if I can fix this now.

**Comment by IntegerLimit** [comment]
More blocks to add to this list... Coal Coke, maybe more.

**Comment by JustBooom** [comment]
Nice, thanks
