### ISSUE TITLE
[Mod Suggestion] Tool Belt

### ISSUE THREAD

**Issue by tyreforhyred** [tracer4b/nomi-ceu#283]
**Is your feature request related to a problem? Please describe.**
It's a simple QoL feature that helps reduce tool clutter in your inventory.

**Describe the solution you'd like**
Adding the Tool Belt mod

**Describe how the solution will work**
I'm a big fan of the bauble compatible tool storage system of [Tool Belt](https://www.curseforge.com/minecraft/mc-mods/tool-belt) and would love to see it included as I feel it fits in very well with the fun and efficient factory tinkering this pack promotes. It gives you 2-9 slots that can be accessed by a hotkey and it is a snappy radial menu rather than hunting and pecking around in satchels. You add additional pouches to the belt by combining them with the belt in an anvil for a scaling xp cost.
It's great for when you want a couple hammers/picks/shovels in your first mining trips, but it really starts to shine when you are using it to store all your configuration tools (multitude of wrenches, screwdriver, soft hammer, crowbar etc).
As an aside I suggest using B:releaseToSwap=true to remove a bit of the tedium of actually having to click the item you're mousing over and instead only having to hold and release the swap key when your cursor is over the item you want. I also use B:displayEmptySlots=true so that your radial menu isn't constantly shifting in size when you have the belt upgraded to max slots. But of course this is all personal preference and others may feel differently.
Thanks for taking the time to read my pitch, hopefully this addition would be in line for the design ethos of the project, and if not then I totally understand!

**Describe alternatives you've considered**
N/A

**Additional context**
[Tool Belt](https://www.curseforge.com/minecraft/mc-mods/tool-belt)

**Comment by IntegerLimit** [comment]
I've had a look, and this seems like it could fit in quite well. Are there any incompatibility issues, bugs, or overpowered glitches that I need to know about, from your time playing with the mod?

**Comment by IntegerLimit** [comment]
Also, I might have to discuss with tracer about this.

**Comment by tyreforhyred** [comment]
the only thing i've noticed is that storage drawers keys aren't natively supported and must be added into the whitelist config like this
    # List of items to force-allow placing in the belt. Takes precedence over blacklist.
    S:whitelist <
        storagedrawers:drawer_key
        storagedrawers:shroud_key
        storagedrawers:quantify_key
     >

otherwise i haven't had any issues whatsoever with it, i suppose on the "overpowered" side is that you can swap satchels into the slots? i was wondering if that may lead to some kind of NBT issue if they were all packed into an inventory so i took a fully upgraded satchel with holding IV and filled it with different block types
![image](https://user-images.githubusercontent.com/76914208/224588948-119a10c3-7d5c-4e64-9beb-12aad3412a7a.png)
and then proceeded to clone that satchel and fill a belt with them, and then clone the now full belts to fill up a small storage crate
![image](https://user-images.githubusercontent.com/76914208/224589111-51a5995c-1539-421f-b774-d4b975599568.png)
was able to save and reload the world with no issues, so i'm going to hazard a guess that there isn't much of a concern of it causing world corruption. the belt inventory is kept through upgrading it with additional pouches just fine and nothing seems to lose any data in the process. been playing with this mod for years on different versions of minecraft and it always seems to pleasantly Just Work.

**Comment by IntegerLimit** [comment]
What are the default recipes for the Tool Belt and Tool Pouch?

**Comment by tyreforhyred** [comment]
![image](https://user-images.githubusercontent.com/76914208/224674247-c44f0b0e-a9e1-4f9f-8525-2a479cc53e37.png)
![image](https://user-images.githubusercontent.com/76914208/224674282-1dd352ed-fcf9-4670-a042-bef84b9265a9.png)

nothing crazy, the default recipe is just some iron leather and string, and then iron replaced with gold for the pouches. upgrading the belt from 2 slots all the way up to 9 takes ever increasing xp levels in the anvil, the values being
3 5 8 12 15 20 30.
the butchery knife having innate looting 3 again should mean there's plenty of leather to go around, and early game i ended up with plenty of levels with all the furnace smelting of iron, gold and redstone.

**Comment by IntegerLimit** [comment]
Done.
