### ISSUE TITLE
"Easy" Mode

### ISSUE THREAD

**Issue by EpicPuppy613** [tracer4b/nomi-ceu#285]
**Is your feature request related to a problem? Please describe.**
Not really, but its related to everyone who doesn't like spending their time endlessly mining for ores.

**Describe the solution you'd like**
A quest or mode of some sort that gives the player a infinite drawer of nomicoins. This would allow for around the same progression while completely eliminating the need for mining.

**Describe how the solution will work**
Probably a quest or mode that you can toggle that gives the player a 2x2 storage drawer that contains all of the different types of nomicoins and a infinite vending upgrade.

**Describe alternatives you've considered**
You could just cheat in the items yourself, but I think a dedicated way to do it in the modpack without cheats would be nice.

**Additional context**
I've been playtesting it for a while now and it seems that this would be a good way to help people transition from a standard modpack to a GregTech modpack as it heavily encourages batch-crafting and other good practices when playing a modpack with a lot of microcrafting.

**Comment by IntegerLimit** [comment]
Interesting idea, could be implemented. Unsure at the moment.

**Comment by IntegerLimit** [comment]
I'm sorry, but tracer has declined this idea. You could have this yourself in your world, but tracer doesn't want it in the pack.

**Comment by v-tl** [comment]
@EpicPuppy613 - To be fair, nomicoins are already infinite thanks to the Bounty Board. You can fulfil bounties that ask only for wooden or stone widgets from the very beginning, and you can spam bounties by repeatedly placing and breaking the bounty board. It's some work, but removes any need for mining which is a fair compromise IMO - in fact, my favorite way to play Omni / Nomi / Nomi-CEu is to start in an empty Superflat world (3;minecraft:air;1;), spawn a small bedrock platform, and edit the very first quest's rewards to be a bucket of lava, a bucket of water, half a stack of dirt, a sapling, and a Nomiquarter (technically, the quarter is optional but that's trickier and even more grind).
