### ISSUE TITLE
Materials used for Exotic Materials Catalyst differ from those shown in the quest book

### ISSUE THREAD

**Issue by Namacack** [tracer4b/nomi-ceu#286]
**Pack Version:**
1.5.2

**Launcher:**
GDLauncher

**Mode:**
NM

**Environment:**
Multiplayer

**Description:**
The quest following Exotic Materials Catalyst has Pulsating Iron, but Rhodium Plated Lumium-Palladium is actually used in the recipe instead.

**Expected Behavior:**
Both indicate/use the same material (probably Rhodium Plated Lumium-Paradium)

**Steps To Reproduce:**
1.Check the End Game tab in the Quest Book
2.Check the Exotic Materials Catalyst recipe in HEI

**Comment by IntegerLimit** [comment]
Huh, I'll have a look and investigate this. Thanks!
