### ISSUE TITLE
Privative Blast Furnace is missing recipes 

### ISSUE THREAD

**Issue by fffxc2** [tracer4b/nomi-ceu#287]
**Pack Version:**
Release v1.5.2

**Launcher:**
MultiMC 0.7.0-3732

**Mode:**
Normal mode

**Environment:**
Single player, no other changes

**Description:**
If you view recipes for the PBF there is only one recipe (2 Wrought Iron + 1 Coke dust). The other PBF recipes defined in normalmode.zs do not appear.

**Expected Behavior:**
There should be six recipes for the PBF, using coal, coal dust, charcoal, charcoal dust, coke and coke dust as the respective fuels.

**Steps To Reproduce:**
Launch the pack, create a new world. Look up PBF recipes, note there is only a single recipe for Wrought Iron with coke.

**Crash Log:**
No crash log because the issue doesn't cause a crash.

**Screenshots:**
![pbf issue](https://user-images.githubusercontent.com/5497199/224860769-60989444-c4c8-4b2e-a142-2a8ddbfb0423.JPG)

**Comment by IntegerLimit** [comment]
This has been fixed, and will be released with 1.5.3 soon.
