### ISSUE TITLE
1.5.2 Server Crash on Restart

### ISSUE THREAD

**Issue by v-tl** [tracer4b/nomi-ceu#293]
**Pack Version:**

1.5.2

**Launcher:**

Server

**Mode:**

Normal Mode

**Environment:**

Plain server from CurseForge.

**Description:**

Server 1.5.2 (default from CurseForge) starts fine once (creates the world etc.), but after a restart it always crashes (see crash log below). 1.5.1 doesn't have this issue.

Seems different from #289 so reporting it separately just in case. 

**Expected Behavior:**

Server should start / restart normally.

**Steps To Reproduce:**

Run 1.5.2 server, shut it down, try restarting.

**Crash Log:**

https://textbin.net/grrskqyevf

**Screenshots:**

N/A

**Comment by 0xC4DE** [comment]
Attempted to recreate with a fresh install, no luck.
What is your output for `java --version`, does this happen to a fresh world?

It seems to be having a fit about some of your fluxed armor/tools having duplicate property fields. Not sure how that has occurred

**Comment by v-tl** [comment]
This is from the server's logs:
Java is OpenJDK 64-Bit Server VM, version 1.8.0_312, running on Linux:amd64:3.10.108, installed at /opt/java/openjdk

I'm running the server in a docker container (the base image is https://registry.hub.docker.com/r/itzg/minecraft-server/, java8-multiarch). It happens on all new worlds, yeah, but only after a restart. I'd suspect the setup but I've used it to run 1.5.1 without any issues (and rolling back to that version fixed the problem).

**Comment by 0xC4DE** [comment]
I happen to use the same setup. I will test using that specifically sometime today. I use the strategy of pointing the docker-compose file to the zip file, ensuring the old directory is deleted first.

**Comment by 0xC4DE** [comment]
Could not replicate the issue. Please ensure you are using a completely fresh installation.

**Comment by IntegerLimit** [comment]
> Could not replicate the issue. Please ensure you are using a completely fresh installation.

Did you try restarting the server?

**Comment by 0xC4DE** [comment]
> > Could not replicate the issue. Please ensure you are using a completely fresh installation.
> 
> Did you try restarting the server?

Yeah. I created the server, turned it off turned it back on, for good measure I did docker-compose restart as well.

**Comment by 0xC4DE** [comment]
> Try downloading it from CurseForge, maybe that's the problem.

I use the zip file from curseforge, but I dont provide it the link. I just directly use the zip, its worth trying but at that point wouldn't it transition into an issue with itzg/miencraft-server docker container?

**Comment by v-tl** [comment]
Thanks for looking into this. I was using AUTO_CURSEFORGE TYPE for the server, and fresh installs of 1.5.2 kept crashing upon restart, but pinning the version to 1.5.1 and then upgrading to 1.5.2 seems to have helped - I've restarted the server a few times and all's good.

**Comment by 0xC4DE** [comment]
Hm. Yeah maybe it is a bug with itzg/minecraft-server then. I'm at least 99% sure the Curseforge zip is fine.

**Comment by IntegerLimit** [comment]
Huh, thats weird. At least its working now.
