### ISSUE TITLE
Texture animations don't work

### ISSUE THREAD

**Issue by KaxelOleg** [tracer4b/nomi-ceu#294]
I understand that most likely this question should not be raised here, but I still decided to ask it here, because perhaps someone has encountered this. The problem is that there are no animations of textures of both objects and blocks. I'm talking about the animation of the mixer, collector, crusher, etc., including even the animation of fire. Everything is just off, nothing is moving. I checked in the game settings, I have animations enabled, I tried to remove various mods, including betterFps, but for some reason nothing is moving anyway. This problem is not only with Gregtech or fire, but also with other mods where there are texture animations. Animations are simply missing. I'm sure it's some kind of mod doing this, but I don't know which one, I tried it myself. Can someone tell me what's the matter?

**Comment by IntegerLimit** [comment]
This is intended, as textures do something to people with AMD GPUs. However, you can simply enable animated textures (not recommended for people with AMD GPUs), by setting `B:onDemandAnimatedTextures` in the config of *lolasm* (found in your config folder, called `lolasm.cfg`) to false. Its near the bottom, in the last section, called `textures`.

Please note that this config option only shows up when you have run the game once. However, you can simply copy a version from your old instances over when you are updating, and that will work just fine.

**Comment by KaxelOleg** [comment]
> 



> This is intended ish, as animated textures, cause lag issues with AMD GPUs. However, you can simply enable animated textures (not recommended for people with AMD GPUs), by setting `B:onDemandAnimatedTextures` in the config of _lolasm_ (found in your config folder, called `lolasm.cfg`) to false. Its near the bottom, in the last section, called `textures`.
> 
> Because of the lag issues this may cause, we do not want to have this as the default.
> 
> Please note that this config option only shows up when you have run the game once. However, you can simply copy a version from your old instances over when you are updating, and that will work just fine.
> 
> Also, the textures of blocks should animate without this config set to false, when you have your crosshair over them.

Thanks! This solved my problem. I will know

**Comment by kafuuchino-desu** [comment]
I'm having the same problem here, I confirmed that `B:onDemandAnimatedTextures` is both set to false on both the client and the server, but the animation is still missing, neither when I have my crosshair over it, but all multis have proper animation no matter this is on or not (steam grinder and EBF).

**Comment by Acemavie234** [comment]
I also have the same problem I have set the `B:onDemandAnimatedTextures` on borh the server and client but my single blocks still do not make any noise or animate when running, but all the multiblocks do.

**Comment by Folanlron** [comment]
If you both are on 1.6 the animations/sounds are borked on that version.

Update to beta3a or beta4 and it will fix the problems.

If you are using aeternos for server host, nothing we can do about the fact that they don't allow beta versions on there servers.

**Comment by CmmmmmmLau** [comment]
version 1.6.1-beta-4
when `B:onDemandAnimatedTextures` set to true, animations still not working even with put my crosshair on blocks.
but only need setting to false on client side and able to get animations work in server.

**Comment by TheAirBlow** [comment]
> This is intended ish, as animated textures, cause lag issues with AMD GPUs without updated drivers. However, you can simply enable animated textures (not recommended for people with AMD GPUs), by setting `B:onDemandAnimatedTextures` in the config of _lolasm_ (found in your config folder, called `lolasm.cfg`) to false. Its near the bottom, in the last section, called `textures`.
> 
> Because of the lag issues this may cause, we do not want to have this as the default.
> 
> Please note that this config option only shows up when you have run the game once. However, you can simply copy a version from your old instances over when you are updating, and that will work just fine.
> 
> Also, the textures of blocks should animate without this config set to false, when you have your crosshair over them.

It is not animated textures, mind you (kind of). Installing optifine and doing disabling GT shaders/bloom lets you disable Animated Terrain, which is in my experience, the issue causing bad frames. I use linux and I have an AMD card.

**Comment by TheAirBlow** [comment]
also, lolasm xD

**Comment by TheAirBlow** [comment]
> version 1.6.1-beta-4 when `B:onDemandAnimatedTextures` set to true, animations still not working even with put my crosshair on blocks. but only need setting to false on client side and able to get animations work in server.

Also, animations are client-side... Server doesn't render anything.

**Comment by CmmmmmmLau** [comment]
> > version 1.6.1-beta-4 when `B:onDemandAnimatedTextures` set to true, animations still not working even with put my crosshair on blocks. but only need setting to false on client side and able to get animations work in server.
> 
> Also, animations are client-side... Server doesn't render anything.

I have no idea why u reply me, I just want to reiterate that only need change it on client side because someone done it on both side before.
