### ISSUE TITLE
Synthesis of table

### ISSUE THREAD

**Issue by tryforyou** [tracer4b/nomi-ceu#30]
Pack Version:
1.2.3

Description:
I started the expert mode according to your method, but the synthetic table of mining machines has both ordinary mode and expert mode

Screenshots:
![1](https://user-images.githubusercontent.com/99582227/169018457-4f28aa2b-a25f-4494-a428-63c8888f2e33.png)
![2](https://user-images.githubusercontent.com/99582227/169018458-0cf16b52-45a1-4eb5-8022-8ebac4a06411.png)

**Comment by tracer4b** [comment]
Are there any errors which occur on loading the world?

**Comment by tracer4b** [comment]
Found the issue, it's due to GTCEu slightly changing the default recipe of ore drilling plant.
This will be resolved next update. Thank you
