### ISSUE TITLE
crash on world load

### ISSUE THREAD

**Issue by AKAASH297** [tracer4b/nomi-ceu#300]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.5.2.

**Pack Version:**
1.5.2

**Launcher:**
CF

**Mode:**
NM

**Environment:**
SP

**Description:**
Title

**Expected Behavior:**
load the world

**Steps To Reproduce:**
i have no clue i log out of a world, sleep, wake up and boom, world borked

**Crash Log:**
https://mclo.gs/RWCkZMQ

**Screenshots:**
NA

**Comment by 0xC4DE** [comment]
Have you tried to 
"delete the 'EnderStorage' folder Here: C:\Users\********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\NomiFactory\EnderStorage"
before?

**Comment by AKAASH297** [comment]
> Have you tried to "delete the 'EnderStorage' folder Here: C:\Users********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\NomiFactory\EnderStorage" before?
> 
> Just making sure this is a one-time and not perpetual issue. Keep in mind this action will probably delete all contents of enderchests, backup your world before doing it

no i havent, it happend to me yesterday too, but i made a recent-ish backup and booted that

**Comment by 0xC4DE** [comment]
Weird. if it happens again, try that fix. 

Something might be corrupting the file. No real way to tell. I'll see if someone else has more insight

**Comment by AKAASH297** [comment]
> Weird. if it happens again, try that fix.
> 
> Something might be corrupting the file. No real way to tell. I'll see if someone else has more insight

alright ill just test out your fix.

**Comment by AKAASH297** [comment]
> Have you tried to "delete the 'EnderStorage' folder Here: C:\Users********\curseforge\minecraft\Instances\Nomifactory (GTCEu Port)\saves\NomiFactory\EnderStorage" before?
> 
> Just making sure this is a one-time and not perpetual issue. Keep in mind this action will probably delete all contents of enderchests, backup your world before doing it. (I ask because if you have and this happens often, could be a bigger issue)

Well, doing this worked, i dont know if its long term or not. thank you

**Comment by IntegerLimit** [comment]
Usually this happens because your world has somehow corrupted. Best ways to fix this are:
1. Restore from a backup
That's pretty much it, although if deleting specific files works for you, you can do it like that too.

**Comment by IntegerLimit** [comment]
Please comment if restoring from a backup didn't work, and I'll re-open this.
