### ISSUE TITLE
Maintenance Hatch

### ISSUE THREAD

**Issue by TeslaWP** [tracer4b/nomi-ceu#303]
My maintenance hatches all suddenly turned into Among Us wire game. Very nice april fools joke 👍 . Now how do I undo it without resetting my system time?
![2023-04-01_15 51 16](https://user-images.githubusercontent.com/91423359/229290052-768dbea0-fa85-4795-aae5-5150539a0842.png)

**Comment by IntegerLimit** [comment]
Um, GT thing, should be fixed now, just have to wait it out. Also, the game also actually fixes maintenance problems.
