### ISSUE TITLE
Draconic energy storage multiblock does not accept GT draconium blocks

### ISSUE THREAD

**Issue by oliwier509** [tracer4b/nomi-ceu#304]
**Pack Version:**
1.5.2

**Launcher:**
CurseForge launcher

**Mode:**
Normal mode

**Environment:**
Singleplayer

**Description:**
Draconic energy storage multiblock does not accept GT draconium blocks

**Expected Behavior:**
The Draconic energy storage multiblock accepts GT draconium blocks

**Steps To Reproduce:**
Build the Draconic energy storage multiblock and use the GT draconium blocks

**Crash Log:**
N/A

**Screenshots:**
![229292049-785dd6ff-6733-4df9-adbc-3d395033b3a4](https://user-images.githubusercontent.com/53867161/229305520-3837c6a0-63a1-41e6-9c65-3ea174c1c878.png)

**Comment by IntegerLimit** [comment]
Launcher?
Actually important. If CurseForge, that's the problem. Try a different one, such as Prism Launcher.

**Comment by oliwier509** [comment]
it is curseforge

**Comment by IntegerLimit** [comment]
As I said in my previous comment, try another launcher, like Prism Launcher, and then tell me if it still happens.

**Comment by oliwier509** [comment]
the bug doesn't appear on the Prism Launcher

**Comment by IntegerLimit** [comment]
Ok.
