### ISSUE TITLE
Suggestion: Make Photovoltaic Cell IV Take Any Blue Lense

### ISSUE THREAD

**Issue by schneid3306** [tracer4b/nomi-ceu#31]
Hello! I just updated to 1.2.3a and was looking at the new solar recipes. I noticed that the Photovoltaic Cell IV takes Blue Topaz lenses. There is currently no passive/automated way to get Blue Topaz. With Blue Sapphire, you can get small dusts from centrifuging lava. The only Topaz from Micro Miners is the Perfect Topaz, which means no dust washing for small piles of blue topaz. I was hoping you'd consider any blue lens for the Photovoltaic Cell IV, or maybe consider adding in a way to passively get Blue Topaz.

Thanks for the consideration!

**Comment by tracer4b** [comment]
Resolved in version 1.3
