### ISSUE TITLE
Question: WIll stabilized microverse miner ever get used?

### ISSUE THREAD

**Issue by foxwhite25** [tracer4b/nomi-ceu#32]
I saw the recipies for stabilized microverse miner by usage of normal miner, and saw they have unlimited uses.
Although that might be too overpowered, but is it planned feature for future, or a removed feature?

It have no usage and is hidden from jei.

**Comment by Folanlron** [comment]
Those are for Hard Mode, it's the reward for getting hearts sense there is no Creative Tank in Hard Mode.

**Comment by foxwhite25** [comment]
Ah ok, make sense
