### ISSUE TITLE
Large engraving machine is outputting only one wafer regardless of the type of wafer used as part of the recipe

### ISSUE THREAD

**Issue by phytopius** [tracer4b/nomi-ceu#38]
**Pack Version:**
1.2.3

**Description:**
The large engraving machine is disregarding the type of wafer which was used as part of the recipe.
No matter which type was input (normal, Glowstone-doped, Naquadah-droped) the output will always only be one wafer.

**Expected Behavior:**
Output the amount of wafers shown in the recipe. 
in general that is 1 for normal wafer, 4 for glowstone-doped, 8 for naquadah-doped

**Steps To Reproduce:**
Put recipe materials into input hatch of Large Engraving Machine. Check o utput

**Screenshots:**
![image](https://user-images.githubusercontent.com/16293118/171287792-1b23ca70-c135-4188-8763-b4977fb03159.png)
![image](https://user-images.githubusercontent.com/16293118/171287852-c937fc04-1309-4774-adef-8e6d55f17e4a.png)

**Comment by tracer4b** [comment]
Should have been resolved in the latest GT versions
