### ISSUE TITLE
Quest "Element 090: Thorium" asks for wrong type of Thorium

### ISSUE THREAD

**Issue by phytopius** [tracer4b/nomi-ceu#40]
**1.2.3**

**Description:**
The quest "Element 090: Thorium #660 which is a requirement for  the quest "Mote of Omnium" #280 asks for 64 Stabilized Thorium.
Stabilized Thorium is not part of the recipe for "Mote of Omnium"

**Expected Behavior:**
Replace the item "Stabilized Thorium" with "Thorium  Ingots" which is the item that is used to craft the "Mote of Omnium

**Steps To Reproduce:**
Look up quest chain in questlog

**Screenshots:**
![image](https://user-images.githubusercontent.com/16293118/172117643-67837322-0ce9-4609-b4ae-0ab9ef425231.png)
![image](https://user-images.githubusercontent.com/16293118/172117698-6a354d41-4595-43d8-b5ae-9387c69c541f.png)
![image](https://user-images.githubusercontent.com/16293118/172117726-990dcaeb-bcf6-4ab0-832d-25936a90fcee.png)

**Comment by tracer4b** [comment]
Resolved in 1.3.4
