### ISSUE TITLE
Impossible to produce Aluminium ingot

### ISSUE THREAD

**Issue by z0the** [tracer4b/nomi-ceu#42]
**Pack Version:**
1.2.3 Release, from Curse Forge

**Description:**
I just recently started to go through the assembly and ran into a problem, I can't produce aluminum. According to the scenario, it is produced only in Blast Furnace, and requires MV electricity, and aluminum is needed to get MV electricity, so this is just a dead end. I'll attach a screenshot. The same problem is with Energetic Alloy from EnderIO.

**Expected Behavior:**
It should be possible to produce aluminum and Energetic Alloy in Blast Furnace using only LV electricity and those resources that can be obtained at an early stage

**Steps To Reproduce:**
Open the aluminium ingot recipe in JEI

**Screenshots:**
![screen](https://user-images.githubusercontent.com/57135174/172224764-aa1ff565-7248-4e1a-821d-72796b2b0406.jpg)

![image](https://user-images.githubusercontent.com/57135174/172224990-9ef7d858-95ab-4b32-8c85-679795a036f2.png)

**Comment by tracer4b** [comment]
Please read the quest book, you need to use 2x LV Energy Hatch with the Blast Furnace in order to reach MV power.

**Comment by z0the** [comment]
> Please read the quest book, you need to use 2x LV Energy Hatch with the Blast Furnace in order to reach MV power.

Thank you very much, forgive me for my carelessness
