### ISSUE TITLE
Missing granite grinding into thorium recipes? 

### ISSUE THREAD

**Issue by foxwhite25** [tracer4b/nomi-ceu#44]
**Pack Version:**
[1.2.3a](https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/3790974)

**Description:**
Maybe this is intended or an oversight, but this granite crush into black granite dust and thorium is kinda important to the whole end-game fission economy to produce enough TBU fuel. 

You can still crush black granite but that is not renewable, and granite can be renewable in an igneous extruder. 

**Expected Behavior:**
Granite to thorium or granite to black granite recipes exist.

**Steps To Reproduce:**
Install the pack.

**Comment by Folanlron** [comment]
You need to use the Gregtech Rockbreaker for black granite.

**Comment by tracer4b** [comment]
As mentioned above, use GT Rock Breaker.
