### ISSUE TITLE
Steel drum can hold acid if clicked in machine output slot

### ISSUE THREAD

**Issue by dbridle** [tracer4b/nomi-ceu#46]
Pack Version:
1.2.3a

Description:
Steel drums cannot accept acids, for example, via conduits/pipes.  However, simply clicking the steel drum on the output slot of the machine, overrides the acid restriction.

Expected behaviour:
No fluid should be stored in the drum

To reproduce:

Produce sulfuric acid in a machine (ie distillery)
Click steel drum on the output slot of the machine
Note the sulfuric acid in the steel drum

**Comment by tracer4b** [comment]
Fixed in CEu version 2.3.0, included in version 1.3
