### ISSUE TITLE
LuV miner crashes game

### ISSUE THREAD

**Issue by chris1380** [tracer4b/nomi-ceu#47]
version 1.2.3a

After building the LuV miner, it is unable to open its gui, and right-clicking the controller makes the game generate crash reports without crashing the game, 
Powering the LuV miner completely crashes the game/server. 

**Steps To Reproduce:**
Build a Luv miner and power it

**Crash Log:**
https://pastes.dev/aQ5LrDoKl7

**Comment by chris1380** [comment]
the EV and IV miners also has this problem...

**Comment by chris1380** [comment]
Found that the problem was because I forgot to add a fluid input hatch. But please still fix the crashing.

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).

**Comment by chris1380** [comment]
Reported.
