### ISSUE TITLE
Missing fluids for post tank

### ISSUE THREAD

**Issue by BronsonMagnan** [tracer4b/nomi-ceu#51]
**Pack Version:**
1.2.3

**Description:**
Tankable fluid for graphite missing, required for graphene
Tankable fluid for PU-241 missing from JEI, but does work in tank if you manually melt it. You just cannot click over from JEI

**Expected Behavior:**
PU-241 fluid restored to JEI
Graphite to have a fluid for solidifying, if I recall correctly, this was available in original Nomifactory.

**Steps To Reproduce:**
Browse JEI

**Comment by IntegerLimit** [comment]
@tracer4b confirmed that this is still a problem.

**Comment by tracer4b** [comment]
I tried restoring the Pu-241 fluid to JEI but I have no idea why it didn't work. Both of these are a wontfix tbh
