### ISSUE TITLE
Lost Cities loot gives AE2 Certus dust instead of Gregtech, no recipe to convert

### ISSUE THREAD

**Issue by pat2rome** [tracer4b/nomi-ceu#54]
**Pack Version:**
1.3

**Description:**
Chests in Lost Cities buildings give AE2 Certus Quartz dust, which has no possible use and no conversion recipe to GregTech certus dust, which does have uses.

**Expected Behavior:**
There should be a recipe to convert AE2 certus dust to GregTech certus dust, and GregTech certus dust is what should appear in the loot table.

**Steps To Reproduce:**
Get AE2 certus dust from JEI and see that there's nothing you can do with it.

**Comment by pat2rome** [comment]
The same is also true with EnderIO Dark Steel instead of GregTech, but since you can convert it into GregTech (by crafting it to 9 nuggets and crafting those nuggets into the GregTech ingot) that's not as much of an issue.

**Comment by IntegerLimit** [comment]
Closed with https://github.com/tracer4b/nomi-ceu/commit/ce18dbe46019b78a3d65d7e56663762e8def4490.
