### ISSUE TITLE
Corrupted World? (Can't enter to my world)

### ISSUE THREAD

**Issue by Pala431** [tracer4b/nomi-ceu#55]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.3

**Description:**
Hello, my problem here is that i can't enter into my minecraft world. When the load bar reaches 100, instantly the game closes. 

**Expected Behavior:**
Maybe my world is corrupted (bc my pc shutdown bc the power went out for a second).

**Steps To Reproduce:**
I don't know, but maybe there's a corrupted file so i can delete it.

**Crash Log:**
There's not a crash log for some reason, but instead here's the lastest.log and debug.log
[latest.log](https://github.com/tracer4b/nomi-ceu/files/9078286/latest.log)
[debug.log](https://github.com/tracer4b/nomi-ceu/files/9078287/debug.log)

**Screenshots:*
I don't have any screenshot.

**Comment by tracer4b** [comment]
Seems like an issue with Advanced Rocketry.
Have you visited the Moon at all this playthrough? Try resetting the Advanced Rocketry config files (Delete them and replace them with the AR config files from a fresh install).

**Comment by Pala431** [comment]
> Seems like an issue with Advanced Rocketry. Have you visited the Moon at all this playthrough? Try resetting the Advanced Rocketry config files (Delete them and replace them with the AR config files from a fresh install).
Hello, sorry for late reply, but in my world i only got to beginning.
I didn't touch anything with advanced rocketry, but I did make my base in the void dimension (idk if it has anything to do with it adveanced rocketry but I say so).
I'll try doing what you say, i will reply if it works.

**Comment by Pala431** [comment]
I forgot to update.
Deleting the AR config did not work, but I remembered that this mod has backups so I restored the world from a day before, I went to creative and I made the lost changes in the other world, so problem solved? Thanks anyway and have a nice day.

**Comment by tracer4b** [comment]
Seems like "routine" corruption to me. All is well anyway since you had the backup 🙂
