### ISSUE TITLE
The Empowered Restonia Crystal Block cannot be crafted

### ISSUE THREAD

**Issue by GreatCoffee** [tracer4b/nomi-ceu#57]
**Pack Version:**
1.3.5

**Description:**
The Empowered Restonia Crystal Block is used to craft the Particle Generator, which is a key material of the Energy Core Stabilizer, for a tier seven microverse ship and a Creative RF Source.
The present recipe of Empowered Restonia Crystal Block is to empower a Restonia Crystal Block with a Conflux Component, a Red Alloy Ingot, an Almandine and a Sulfuric Acid Cell.
However the Sulfuric Acid Cell is not obtainable, as the Empty Cell cannot hold Acids.

**Expected Behavior:**
Either the Sulfuric Acid Cell gets obtainable, or the recipe of Empowered Restonia Crystal Block gets changed. Maybe a vanilla bucket of Sulfuric Acid is a good choice.
The recipe script is located at "/.minecraft/scripts/aa xu2.zx", line 18.
`mods.actuallyadditions.Empowerer.addRecipe(<actuallyadditions:block_crystal_empowered>, <actuallyadditions:block_crystal>, <metaitem:gemAlmandine>, <metaitem:ingotRedAlloy>, <metaitem:fluid_cell>.withTag({Fluid: {FluidName: "sulfuric_acid", Amount: 1000}}), <extendedcrafting:material:19>, 1000000, 400);`

Edit:
The recipe using Crafting Core or Combination Package Crafter should also be changed. It's located at "/.minecraft/scripts/CraftingCoreUpgrade.zs", line 29.

**Comment by mczph** [comment]
https://github.com/tracer4b/nomi-ceu/pull/58
