### ISSUE TITLE
Some recipes bugs in expert mode

### ISSUE THREAD

**Issue by KuroPeach** [tracer4b/nomi-ceu#62]
Some recipes bugs in expert mode. 

Sulfuric acid can not be used in ordinary fluidcell, I changed to glass fluidcell

aa xu2.zs      //Empowered Restonia
mods.actuallyadditions.Empowerer.removeRecipe(<actuallyadditions:item_crystal_empowered>);
mods.actuallyadditions.Empowerer.removeRecipe(<actuallyadditions:block_crystal_empowered>);
mods.actuallyadditions.Empowerer.removeRecipe(<moreplates:empowered_restonia_gear>);
mods.actuallyadditions.Empowerer.addRecipe(<actuallyadditions:block_crystal_empowered>, <actuallyadditions:block_crystal>, <metaitem:gemAlmandine>, <metaitem:ingotRedAlloy>, <metaitem:fluid_cell.glass_vial>.withTag({Fluid: {FluidName: "sulfuric_acid", Amount: 1000}}), <extendedcrafting:material:19>, 1000000, 400);

CraftingCoreUpgrade.zs   	#Empowered Restonia
	<actuallyadditions:block_crystal_empowered> : [
		<actuallyadditions:block_crystal>,
		<ore:ingotRedAlloy>,
		<ore:gemAlmandine>,
		<metaitem:fluid_cell.glass_vial>.withTag({Fluid: {FluidName: "sulfuric_acid", Amount: 1000}}),
		<extendedcrafting:material:19>		//conflux component
	],

Beryllium oxide recipes conflicts with beryllium recipes，I switched to using liquid oxygen. 

expert_processing.zs      // Beryllium Oxide
arc_furnace.recipeBuilder()
    .inputs(<ore:dustBeryllium>)
    .fluidInputs(<liquid:liquid_oxygen> * 100)
    .outputs(<metaitem:ingotBerylliumOxide>)
    .duration(640).EUt(30).buildAndRegister();

**Comment by KuroPeach** [comment]
oh, no. liquid_oxygen can't input arc_furnace

**Comment by tracer4b** [comment]
First issue has been fixed in #58

**Comment by KuroPeach** [comment]
thanks, The following can be tried to change into a chemical reactor

// Beryllium Oxide
chemical_reactor.recipeBuilder()
    .inputs(<ore:dustBeryllium>)
    .fluidInputs(<liquid:oxygen> * 1000)
    .outputs(<metaitem:dustBerylliumOxide>)
    .duration(200).EUt(480).buildAndRegister();
