### ISSUE TITLE
Gregtech blocks do not properly render on Storage Drawers framed drawers

### ISSUE THREAD

**Issue by pat2rome** [tracer4b/nomi-ceu#63]
**Pack Version:**
1.3.5

**Description:**
Gregtech blocks do not properly render their color when used as a part of any Storage Drawers (or Framed Compacting Drawers) framed drawer. The saturation seems to still work properly (not sure if that is the correct term), but the color just renders as white.

**Expected Behavior:**
The framed drawer should take on the full appearance of the blocks used to make the framing, color included.

**Steps To Reproduce:**
Place a framing table into the world, put any type of framed drawer in the leftmost slot in the GUI, then place any Gregtech "block of [material] in one or more of the remaining input slots. Observe the white color no matter what block is chosen.

**Screenshots:**
![Framing with Gregtech blocks](https://i.imgur.com/M6AozH5.png)

I placed the drawer in the world to ensure that this wasn't just an issue with how it renders on the table, and you can see that it also does not render properly as a block placed in-world. A second but more minor issue is that the blocks render too large on the table.

![Framing with vanilla blocks](https://i.imgur.com/a5Ys94G.png)

Here you can see the expected behavior, using blocks of gold and iron from vanilla Minecraft. Also note the size at which the blocks render, with no overlapping and subsequent z-fighting.

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).
