### ISSUE TITLE
Empowered Restonia Uncraftable

### ISSUE THREAD

**Issue by hucking** [tracer4b/nomi-ceu#64]
**Pack Version:** 1.3.5

**Description:**
Sulfuric acid cells are required for the empowered restonia recipe, however the cells themselves cannot contain acids at the moment.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1339552/180590373-f2f2fd7a-0fe7-400b-b13b-54c9287c21c8.png)

**Comment by tracer4b** [comment]
Fixed in #58
