### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by WaterMo** [tracer4b/nomi-ceu#65]
**Pack Version:**
1.31&1.35

**Description:**
When I close and open the questbook , there will be no response

**Crash Log:**

[log.log](https://github.com/tracer4b/nomi-ceu/files/9222700/log.log)

**Comment by WaterMo** [comment]
Also , if i add the vanillaFix , the game would not start up

**Comment by Caedis** [comment]
Make sure you are not in edit mode by running `/bq_admin edit off` and you are on the latest quest book by running `/bq_admin default load` (may have to enable cheats via starting the lan server temporarily)

VanillaFix is not needed with CensoredASM
