### ISSUE TITLE
Configurable maintenance hatch does not increase processing speed (GTCEu Expert Mode)

### ISSUE THREAD

**Issue by Anymn** [tracer4b/nomi-ceu#68]
**Pack Version:**
Version 1.3.5

**Description:**
When using a configurable maintenance hatch for a Blast Furnace, you should be able to increase the processing speed at the cost of a higher maintenance frequency according to the description. However, the recipe processing time does not change, regardless of the settings.

**Expected Behavior:**
I expected an increased processing speed when changing the settings on the configurable maintenance hatch.

- **Steps To Reproduce:**
- Create a blast furnace. 
- Add a Configurable Maintenance hatch on it.
- Set duration to 0,9

**Crash Log:**
N/A

**Screenshots:**
![afbeelding](https://user-images.githubusercontent.com/39721894/183086253-c84f0973-dbcb-4f45-928c-387804662b03.png)

![afbeelding](https://user-images.githubusercontent.com/39721894/183086356-7b406f11-d01b-40ce-98b7-152bffdb10b6.png)

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).
