### ISSUE TITLE
There is no machine recipes for the stickTreatedWood. 

### ISSUE THREAD

**Issue by KuroPeach** [tracer4b/nomi-ceu#69]
There is no machine recipes for the stickTreatedWood, and the AE orderly recipes stuck in the return saw. 
![image](https://user-images.githubusercontent.com/19620848/183275289-2bba4df8-81ef-41a6-8704-a420d99a4a0c.png)
![image](https://user-images.githubusercontent.com/19620848/183275298-04230a5a-2bfe-44c9-bc68-07abb6a3fc5a.png)

**Comment by pat2rome** [comment]
There's also no machine recipes for treated wood fluid pipes.

**Comment by KuroPeach** [comment]
But it doesn't involve automation.  :)
