### ISSUE TITLE
GT Axe with Auto-Smelt enchantment smelts only first log.

### ISSUE THREAD

**Issue by idc7** [tracer4b/nomi-ceu#71]
Pack Version:
Version 1.3.5

Description:
GT Axe with auto-smelt enchantment (EnderCore) does not work correctly with the lumberaxe functionality.
It will smelt only the first block, all blocks broken by the lumberaxe function will be normal log.

Also CoFH Smelting enchant can be applied to a vanilla Axe, but not a GT axe.

**Comment by tracer4b** [comment]
This issue lies with GTCEu; please report it directly to them [here](https://github.com/GregTechCEu/GregTech).
