### ISSUE TITLE
Items can be inserted into Creative Quantum Tank

### ISSUE THREAD

**Issue by dbridle** [tracer4b/nomi-ceu#73]
Pack Version:
1.3

Description:
If an automated process, such as ME Interface is placed next to a quantum tank, it will pull the items in for a pattern.

Expected Behavior:
Quantum tanks should not import items (and possibly not liquids? Not sure if an automated setting of a Creative QTank is required).

Steps To Reproduce:
Put an ME Interface next to a quantum tank, setup a recipe.  Breaking the tank, releases the items.  If more than 1 item is inserted, breaking the interface spills the remaining items out.

**Comment by tracer4b** [comment]
Intended behaviour, items like tanks can be inserted to fill them with liquid
