### ISSUE TITLE
Wooden Crate Recipe in Assembler broken

### ISSUE THREAD

**Issue by danirpg** [tracer4b/nomi-ceu#86]
**Pack Version:**
1.4
**Description:**
The wooden crate in the assembler cannot be maded since it conflict with the fence recipe also maded in the assembly machine with circuit number 1

**Expected Behavior:**
Wodden crate craft

**Steps To Reproduce:**
Put the recipe of wodden crate (from gregtech) in the assembly machine to see the wooden fences crafted instead.

**Screenshots:**

![image](https://user-images.githubusercontent.com/15187376/187758793-082d6759-d43b-43d6-9429-d646c5aa2f02.png)
![image](https://user-images.githubusercontent.com/15187376/187758958-073247d4-562a-4bd9-b70e-a1242589e30f.png)

**Comment by tracer4b** [comment]
This is a CEu issue, I'll forward to them
