### ISSUE TITLE
Launch Pad recipe broken

### ISSUE THREAD

**Issue by danirpg** [tracer4b/nomi-ceu#88]
**Pack Version:**
1.4

**Description:**
Recipe of Launch Pad is empty

**Expected Behavior:**
Recipe not empty?

**Steps To Reproduce:**
Search in HEI the recipe of launch pad

**Screenshots:**
![image](https://user-images.githubusercontent.com/15187376/187964068-751fc538-f4ee-427e-802f-7d20590f4fb8.png)

**Comment by tracer4b** [comment]
Fixed in 6f2677a6e0f713089a3e38711be95b602a90d7b3
