### ISSUE TITLE
Nomifactory CEu (hard) 1.4 certus quartz+charger quest uncompletable

### ISSUE THREAD

**Issue by antrobot1234** [tracer4b/nomi-ceu#89]
![image](https://user-images.githubusercontent.com/21179158/188049848-64b16780-7030-4e4e-81d5-c1b80186123a.png)

**Comment by EmmieAndreas** [comment]
Certus quartz only spawns on the moon or the nether, and you're gonna have to buy what you need until you can get there.
Search Certus Quartz instead.

**Comment by tracer4b** [comment]
Closed in #94

**Comment by felix-schneider** [comment]
This is still the case in 1.4.2 Hard Mode
I reloaded the questbook but the quest still specifically requests AE2 Certus Quartz. Seems like this was fixed in Normal Mode only.
