### ISSUE TITLE
[suggestion] Recommend an AE attachment, is very helpful for fluid recipes

### ISSUE THREAD

**Issue by KuroPeach** [tracer4b/nomi-ceu#90]
Recommend an AE attachment, which is very helpful for fluid recipes. 

https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework

![image](https://user-images.githubusercontent.com/19620848/188105994-6b002524-b2c5-4a73-a993-421ce39e9b15.png)

**Comment by tracer4b** [comment]
Don’t really want to add AE2 fluid crafting to the pack since it isn’t needed, but I’m open to adding compatibility scripts for those who choose to add it
