### ISSUE TITLE
quistion

### ISSUE THREAD

**Issue by mightydanp** [tracer4b/nomi-ceu#91]
in the hard mode there was
The Steam Age. I copy pasted the files and override them when i looked there was no steam machines. So what do you mean by The Steam Age?

**Comment by oenone** [comment]
When you applied the hard mode config correctly, the first Chapter (Genesis) should look like this:
![grafik](https://user-images.githubusercontent.com/437919/189518494-75de4694-ee29-4418-9803-d8b51f362592.png)
note the bronze machines

**Comment by mightydanp** [comment]
i got this
![image](https://user-images.githubusercontent.com/4637469/189528156-1f2901b2-e9f2-4465-9abf-6aaaaa0aa825.png)

**Comment by mightydanp** [comment]
i draged and droped the hardmode configs like you said and then i enabled hard quest but thing changed after that for me

**Comment by mightydanp** [comment]
I got it to work can i write out better instructions for you?

**Comment by tracer4b** [comment]
Assume it's fixed, if not do reopen
