### ISSUE TITLE
"Navigating Petrochem" quest does not accept "Raw Oil"

### ISSUE THREAD

**Issue by antrobot1234** [tracer4b/nomi-ceu#92]
**Pack Version:**
1.4

**Description:**
The quest "Navigating Petrochem" does not accept raw oil as a satisfier. This is an issue since oil deposits give raw oil.

**Expected Behavior:**
both raw oil and oil should be accepted fluids.

**Screenshots:**
![image](https://user-images.githubusercontent.com/21179158/188276557-fb8dc1a9-4346-4a1a-ba2a-82da525cbec0.png)

**Comment by okjijenAbi** [comment]
This oil can be acquired from using Oilsands Dust.

**Comment by okjijenAbi** [comment]
> This oil can be acquired from using Oilsands Dust.

but otherwise, you are right.

**Comment by tracer4b** [comment]
In that case, I should update this quest to accept any of the 4 oil types

**Comment by IntegerLimit** [comment]
This has been fixed, please close this issue. @antrobot1234

**Comment by tracer4b** [comment]
> This has been fixed, please close this issue. @antrobot1234

FYI you can put "Closes #X" in your PR and it'll auto-close the right issue
