### ISSUE TITLE
Gas Charge Pad crashing the game.

### ISSUE THREAD

**Issue by okjijenAbi** [tracer4b/nomi-ceu#96]
Pack Version:
1.4

Description:
Putting any kind of tanks (did not try normal items) to Gas Charge Pad crashes the game.

Expected Behavior:
It should empty the tank to its own inventory.

Steps To Reproduce:
Put a gas charge pad down, put in any tank by shift clicking or dragging, will crash the game.

No screenshots since it just crashes the game back to the main menu or completely. 

Problem is because of the following mods as the crash menu says: AdvancedRocketry, Vulpes Library.

Crash log:
[crash-2022-09-08_20.42.19-client.txt](https://github.com/tracer4b/nomi-ceu/files/9529466/crash-2022-09-08_20.42.19-client.txt)

**Comment by okjijenAbi** [comment]
appearantly opening the gui makes the mod run into a problem, and putting any kind of item crashes the game.

**Comment by Folanlron** [comment]
Pipe the oxygen in, and stand on the pad..

act like the UI doesn't exist ...

**Comment by okjijenAbi** [comment]
doesn't it need rf? waila says it does and connecting cables to it doesnt help much either.

**Comment by tracer4b** [comment]
Alleviated in 82e815873223e7139ff00e141e099668fa088fee.
I can't fix the problem directly.
