### ISSUE TITLE
[Suggestion] Use forming press for inscriber recipes.

### ISSUE THREAD

**Issue by account417** [tracer4b/nomi-ceu#97]
the forming press doesn't have many recipes (only really needed for laminated glass) and from my experience ae2 stuff advanced inscribers tend to be quite buggy. moving the recipes from the inscriber to the forming press could be a good idea

**Comment by IntegerLimit** [comment]
Ehh, the advanced inscribers are alright, and I don't feel like this should be done. I'll have a think about it.
