### ISSUE TITLE
server issues

### ISSUE THREAD

**Issue by FirewallDaProtogen** [tracer4b/nomi-ceu#99]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4

**Description:**
java.lang.NoClassDefFoundError: gregtech/api/recipes/CountableIngredient

**Expected Behavior:**
server starts up as normal

**Steps To Reproduce:**
Setup forge 1.12 server, add the modpack, start the server.

**Crash Log:**
I dont have a client crash log but i can provide the server crash log
[latest.log](https://github.com/tracer4b/nomi-ceu/files/9543104/latest.log)

**Screenshots:**

![image](https://user-images.githubusercontent.com/113303660/189539374-116b4970-69f7-4200-bcf0-b3c3d3ebc839.png)

**Comment by tracer4b** [comment]
Try freshly re-installing the pack server side and see if it still crashes

**Comment by FirewallDaProtogen** [comment]
(sorry, new to github so accidentally closed and reopened it)
@tracer4b i did that and now i get "
Checking java version...

'java' is not recognized as an internal or external command,
operable program or batch file.

The expected java version is 1.8. Not higher, not lower.

Launching the server...

> java -server -Xms4096M -Xmx4096M  -Dlog4j.configurationFile=log4j2_112-116.xml -jar forge-1.12.2-14.23.5.2860.jar

'java' is not recognized as an internal or external command,
operable program or batch file.

> The server has stopped. If it's a crash, please read the output above.

Press any key to continue . . .
"

**Comment by FirewallDaProtogen** [comment]
i got it to work! turns out the problem was the "not recognized as an internal command" or something. idk how to perma fix it, but for now i just changed every time the launcher referenced ' java ' with ' ""C:\Program Files\Java\jdk1.8.0_341\bin\java" '
